// server/quizData.js

// ══════════════════════════════════════════════════════════════
// RAW_QUIZ_DATA
// ──────────────────────────────────────────────────────────────
// 카테고리별 문제 수 요약:
//   드라마          : 16개  (k001~k010, vm05~vm10)
//   가요            : 67개  (p001~p015, kg01~kg20, kb01~kb15, ks01~ks15, vm01, vm04)
//   팝송            : 45개  (w001~w015, wp01~wp30)
//   영화            : 10개  (m001~m005, a003, a006~a010)
//   애니메이션      : 29개  (a001~a002, a004~a005, an001~an025)
//   동요            : 30개  (dy001~dy030)
//   클래식 음악     : 20개  (cl001~cl020)
//   작곡가          : 15개  (cp001~cp015)
//   공연 예술       : 15개  (pa001~pa015)
//   스포츠          : 20개  (sp001~sp020)
//   운송수단        : 20개  (tr001~tr020)
//   악기            : 25개  (in001~in025)
//   동물            : 25개  (an101~an125)
//   계절            : 10개  (se001~se010)
//   자연현상        : 15개  (nt001~nt015)
//   불쾌한 소리     : 15개  (ug001~ug015)
//   직업            : 15개  (jb001~jb015)
//   물건/장소       : 20개  (pl001~pl020)
//   나라            : 20개  (cn001~cn020)
//   언어            : 15개  (lg001~lg015)
//   춤의 종류       : 15개  (dn001~dn015)
//   합계            : 471개
// ══════════════════════════════════════════════════════════════
 
const RAW_QUIZ_DATA = [
  { "id": "k001", "category": "드라마", "youtubeId": "aE0eV2YR51k", "youtubeStart": 55, "youtubeEnd": 65, "hint": "2016년 대히트 군인 드라마", "answers": "'태양의 후예', '태양의후예', 'descendants of the sun'", "difficulty": 1 },
  { "id": "k002", "category": "드라마", "youtubeId": "pcKR0LPwoYs", "youtubeStart": 43, "youtubeEnd": 53, "hint": "불멸의 존재가 주인공인 판타지 드라마", "answers": "'도깨비', 'goblin'", "difficulty": 1 },
  { "id": "k003", "category": "드라마", "youtubeId": "D07Q2k04uCU", "youtubeStart": 60, "youtubeEnd": 70, "hint": "외계인과 사람의 사랑 이야기", "answers": "'별에서 온 그대', '별에서온그대', 'you who came from the stars', 'my love from the star'", "difficulty": 2 },
  { "id": "k004", "category": "드라마", "youtubeId": "O0StKlRHVeE", "youtubeStart": 55, "youtubeEnd": 65, "hint": "작은 포차에서 시작하는 복수극", "answers": "'이태원 클라쓰', '이태원클라쓰', 'itaewon class'", "difficulty": 2 },
  { "id": "k005", "category": "드라마", "youtubeId": "jGGQyqohOaw", "youtubeStart": 60, "youtubeEnd": 70, "hint": "북한에 불시착한 재벌 여자와 군인의 사랑", "answers": "'사랑의 불시착', '사랑의불시착', 'crash landing on you'", "difficulty": 1 },
  { "id": "k006", "category": "드라마", "youtubeId": "bLoO0FSXncg", "youtubeStart": 45, "youtubeEnd": 55, "hint": "쌍문동 골목 친구들의 청춘 이야기", "answers": "'응답하라 1988', '응답하라1988', 'reply 1988'", "difficulty": 2 },
  { "id": "k007", "category": "드라마", "youtubeId": "FcxEI4v8ASY", "youtubeStart": 60, "youtubeEnd": 70, "hint": "구한말 시대 배경의 역사 드라마", "answers": "'미스터 션샤인', '미스터션샤인', 'mr sunshine'", "difficulty": 2 },
  { "id": "k008", "category": "드라마", "youtubeId": "gIM3cz4_Bpw", "youtubeStart": 65, "youtubeEnd": 75, "hint": "1998년 IMF 시절 두 남녀의 성장 이야기", "answers": "'스물다섯 스물하나', '스물다섯스물하나', '25 21'", "difficulty": 2 },
  { "id": "k009", "category": "드라마", "youtubeId": "x-YJTJsVQ_0", "youtubeStart": 50, "youtubeEnd": 60, "hint": "조선시대 좀비 드라마", "answers": "'킹덤', 'kingdom'", "difficulty": 3 },
  { "id": "k010", "category": "드라마", "youtubeId": "uioEi8ZeV9s", "youtubeStart": 20, "youtubeEnd": 30, "hint": "넷플릭스 세계적 히트 서바이벌 드라마", "answers": "'오징어 게임', '오징어게임', 'squid game'", "difficulty": 1 },
  { "id": "vm05", "category": "드라마", "youtubeId": "DuyFRw33NvM", "youtubeStart": 60, "youtubeEnd": 70, "hint": "류선재가 임솔을 위해 부른 자작곡 (선재 업고 튀어 OST)", "answers": "'선재 업고 튀어', '선재업고튀어'", "difficulty": 1 },
  { "id": "vm06", "category": "드라마", "youtubeId": "fBB4MaBybyg", "youtubeStart": 62, "youtubeEnd": 72, "hint": "선재 업고 튀어의 시원한 밴드 곡", "answers": "'선재 업고 튀어', '선재업고튀어'", "difficulty": 2 },
  { "id": "vm07", "category": "드라마", "youtubeId": "oaDN43yANpQ", "youtubeStart": 58, "youtubeEnd": 68, "hint": "눈물의 여왕 OST (크러쉬)", "answers": "'눈물의 여왕', '눈물의여왕'", "difficulty": 2 },
  { "id": "vm08", "category": "드라마", "youtubeId": "H3ryYBoay3c", "youtubeStart": 45, "youtubeEnd": 55, "hint": "눈물의 여왕 통통 튀는 OST (BSS)", "answers": "'눈물의 여왕', '눈물의여왕'", "difficulty": 2 },
  { "id": "vm09", "category": "드라마", "youtubeId": "Iu2KFp9dJ4I", "youtubeStart": 55, "youtubeEnd": 65, "hint": "그 해 우리는 OST (비비)", "answers": "'그 해 우리는', '그해우리는'", "difficulty": 3 },
  { "id": "vm10", "category": "드라마", "youtubeId": "UoBsiQW23IY", "youtubeStart": 48, "youtubeEnd": 58, "hint": "사내맞선 달콤한 OST (멜로망스)", "answers": "'사내맞선', '사내 맞선'", "difficulty": 2 },
  { "id": "p001", "category": "가요", "youtubeId": "gdZLi9oWNZg", "youtubeStart": 46, "youtubeEnd": 56, "hint": "BTS의 영어 곡, 전 세계 1위", "answers": "'다이너마이트', 'dynamite'", "difficulty": 1 },
  { "id": "p002", "category": "가요", "youtubeId": "jeqdYqsrsA0", "youtubeStart": 268, "youtubeEnd": 278, "hint": "아이유의 3단 고음으로 유명한 노래", "answers": "'좋은 날', '좋은날', 'good day'", "difficulty": 1 },
  { "id": "p003", "category": "가요", "youtubeId": "IHNzOHi8sJs", "youtubeStart": 55, "youtubeEnd": 65, "hint": "블랙핑크의 대표곡", "answers": "'뚜두뚜두', 'ddu-du ddu-du'", "difficulty": 1 },
  { "id": "p004", "category": "가요", "youtubeId": "9bZkp7q19f0", "youtubeStart": 50, "youtubeEnd": 60, "hint": "전 세계를 강타한 말춤 노래", "answers": "'강남스타일', 'gangnam style'", "difficulty": 1 },
  { "id": "p005", "category": "가요", "youtubeId": "I3dezFzsNss", "youtubeStart": 47, "youtubeEnd": 57, "hint": "EXO의 으르렁거리는 노래", "answers": "'으르렁', 'growl'", "difficulty": 2 },
  { "id": "p006", "category": "가요", "youtubeId": "11cta61wi0g", "youtubeStart": 50, "youtubeEnd": 60, "hint": "뉴진스의 데뷔곡", "answers": "'하입보이', 'hype boy'", "difficulty": 1 },
  { "id": "p007", "category": "가요", "youtubeId": "c7rCyll5AeY", "youtubeStart": 55, "youtubeEnd": 65, "hint": "트와이스의 샤샤샤 노래", "answers": "'치얼업', 'cheer up'", "difficulty": 1 },
  { "id": "p008", "category": "가요", "youtubeId": "MBdVXkSdhwU", "youtubeStart": 75, "youtubeEnd": 85, "hint": "BTS의 DNA", "answers": "'dna', '디엔에이'", "difficulty": 2 },
  { "id": "p009", "category": "가요", "youtubeId": "4TWR90KJl84", "youtubeStart": 40, "youtubeEnd": 50, "hint": "에스파의 넥스트 레벨", "answers": "'넥스트 레벨', 'next level'", "difficulty": 2 },
  { "id": "p010", "category": "가요", "youtubeId": "tF27TNC_4pc", "youtubeStart": 55, "youtubeEnd": 65, "hint": "싸이의 흠뻑쇼 대표곡", "answers": "'나팔바지'", "difficulty": 3 },
  { "id": "p011", "category": "가요", "youtubeId": "AAbokV76tkU", "youtubeStart": 75, "youtubeEnd": 85, "hint": "빅뱅의 WOW FANTASTIC BABY", "answers": "'판타스틱 베이비', 'fantastic baby'", "difficulty": 1 },
  { "id": "p012", "category": "가요", "youtubeId": "XsX3ATc3FbA", "youtubeStart": 55, "youtubeEnd": 65, "hint": "BTS X 할시 컬래버레이션", "answers": "'작은 것들을 위한 시', 'boy with luv'", "difficulty": 2 },
  { "id": "p013", "category": "가요", "youtubeId": "TgOu00Mf3kI", "youtubeStart": 60, "youtubeEnd": 70, "hint": "아이유 X 슈가 콜라보", "answers": "'에잇', 'eight'", "difficulty": 2 },
  { "id": "p014", "category": "가요", "youtubeId": "Dab4EENTW5I", "youtubeStart": 60, "youtubeEnd": 70, "hint": "스트레이 키즈의 마이로", "answers": "'미로', 'miroh'", "difficulty": 3 },
  { "id": "p015", "category": "가요", "youtubeId": "J-wFp43XOrA", "youtubeStart": 60, "youtubeEnd": 70, "hint": "세븐틴의 아주 Nice", "answers": "'아주 나이스', 'very nice'", "difficulty": 3 },
  { "id": "kg01", "category": "가요", "youtubeId": "pSUydWEqKwE", "youtubeStart": 43, "youtubeEnd": 53, "hint": "뉴진스의 우~ 우우우~", "answers": "'ditto', '디토'", "difficulty": 1 },
  { "id": "kg03", "category": "가요", "youtubeId": "Q3K0TOvTOno", "youtubeStart": 52, "youtubeEnd": 62, "hint": "뉴진스의 달콤한 신곡 (2024)", "answers": "'how sweet', '하우스윗'", "difficulty": 2 },
  { "id": "kg04", "category": "가요", "youtubeId": "Y8JFxS1HlDo", "youtubeStart": 57, "youtubeEnd": 67, "hint": "숨참고 LOVE DIVE", "answers": "'love dive', '러브 다이브'", "difficulty": 1 },
  { "id": "kg06", "category": "가요", "youtubeId": "07EzMbVH3QE", "youtubeStart": 48, "youtubeEnd": 58, "hint": "해야 해야 해야 한입에 널 삼킬게", "answers": "'해야', 'heya'", "difficulty": 2 },
  { "id": "kg07", "category": "가요", "youtubeId": "phuiiNCxRMg", "youtubeStart": 39, "youtubeEnd": 49, "hint": "사건은 다가와 Ah Oh Ay", "answers": "'supernova', '슈퍼노바'", "difficulty": 1 },
  { "id": "kg09", "category": "가요", "youtubeId": "D8VEhcPeSlc", "youtubeStart": 46, "youtubeEnd": 56, "hint": "에스파의 트라우마를 깨는 곡", "answers": "'drama', '드라마'", "difficulty": 2 },
  { "id": "kg10", "category": "가요", "youtubeId": "pyf8cbqyfPs", "youtubeStart": 41, "youtubeEnd": 51, "hint": "Anti ti ti ti fragile", "answers": "'antifragile', '안티프래자일'", "difficulty": 1 },
  { "id": "kg11", "category": "가요", "youtubeId": "hLvWy2b857I", "youtubeStart": 36, "youtubeEnd": 46, "hint": "르세라핌의 오버워치 콜라보 곡", "answers": "'perfect night', '퍼펙트 나이트'", "difficulty": 2 },
  { "id": "kg12", "category": "가요", "youtubeId": "KNexS61fjus", "youtubeStart": 49, "youtubeEnd": 59, "hint": "골반을 튕기는 스마트한 춤", "answers": "'smart', '스마트'", "difficulty": 2 },
  { "id": "kg13", "category": "가요", "youtubeId": "7HDeem-JaSY", "youtubeStart": 58, "youtubeEnd": 68, "hint": "아임 어 퀸카! 아임 어 퀸카!", "answers": "'퀸카', 'queencard'", "difficulty": 1 },
  { "id": "kg14", "category": "가요", "youtubeId": "ATK7gAaZTOM", "youtubeStart": 71, "youtubeEnd": 81, "hint": "미친 연주, 나는 아픈 건 딱 질색이니까", "answers": "'나는 아픈 건 딱 질색이니까', 'fate'", "difficulty": 1 },
  { "id": "kg15", "category": "가요", "youtubeId": "Vk5-c_v4gMU", "youtubeStart": 42, "youtubeEnd": 52, "hint": "슈퍼 이끌림~ (아일릿)", "answers": "'마그네틱', 'magnetic'", "difficulty": 1 },
  { "id": "kg16", "category": "가요", "youtubeId": "2wA_b6YHjqQ", "youtubeStart": 52, "youtubeEnd": 62, "hint": "YG 신인 베이비몬스터의 괴물 같은 데뷔곡", "answers": "'sheesh', '쉬시'", "difficulty": 2 },
  { "id": "kg17", "category": "가요", "youtubeId": "IajeQM00yfE", "youtubeStart": 37, "youtubeEnd": 47, "hint": "키스오브라이프의 끈적한 여름 노래", "answers": "'sticky', '스티키'", "difficulty": 2 },
  { "id": "kg18", "category": "가요", "youtubeId": "7UecFm_bSTU", "youtubeStart": 63, "youtubeEnd": 73, "hint": "엔믹스의 믹스팝 정수", "answers": "'dash', '대시'", "difficulty": 3 },
  { "id": "kg19", "category": "가요", "youtubeId": "SxHmoifp0oQ", "youtubeStart": 51, "youtubeEnd": 61, "hint": "스테이씨의 곰돌이 춤", "answers": "'teddy bear', '테디 베어'", "difficulty": 2 },
  { "id": "kg20", "category": "가요", "youtubeId": "9JFi7MmjtGA", "youtubeStart": 47, "youtubeEnd": 57, "hint": "비비지의 숨겨진 명곡", "answers": "'maniac', '매니악'", "difficulty": 3 },
  { "id": "kb01", "category": "가요", "youtubeId": "QU9c0053UAU", "youtubeStart": 54, "youtubeEnd": 64, "hint": "정국의 빌보드 1위 데뷔곡", "answers": "'seven', '세븐'", "difficulty": 1 },
  { "id": "kb02", "category": "가요", "youtubeId": "nOI67IDlNMQ", "youtubeStart": 46, "youtubeEnd": 56, "hint": "지민의 몽환적인 솔로 1위 곡", "answers": "'like crazy', '라이크 크레이지'", "difficulty": 2 },
  { "id": "kb03", "category": "가요", "youtubeId": "-GQg25oP0S4", "youtubeStart": 61, "youtubeEnd": 71, "hint": "마치 된 것 같아 손오공", "answers": "'손오공', 'super'", "difficulty": 1 },
  { "id": "kb04", "category": "가요", "youtubeId": "zSQ48zyWZrY", "youtubeStart": 49, "youtubeEnd": 59, "hint": "세븐틴의 쿵치팍치 쿵쿵치팍치", "answers": "'음악의 신'", "difficulty": 2 },
  { "id": "kb05", "category": "가요", "youtubeId": "mBXBOLG06Wc", "youtubeStart": 38, "youtubeEnd": 48, "hint": "부석순의 직장인 응원가", "answers": "'파이팅 해야지', '파이팅해야지'", "difficulty": 1 },
  { "id": "kb06", "category": "가요", "youtubeId": "JsOOis4bBFg", "youtubeStart": 43, "youtubeEnd": 53, "hint": "별의별의별의별의 특!", "answers": "'특', 's-class', 's class'", "difficulty": 2 },
  { "id": "kb07", "category": "가요", "youtubeId": "P9tKTxbgdkk", "youtubeStart": 52, "youtubeEnd": 62, "hint": "TXT의 몽환적인 유혹", "answers": "'sugar rush ride', '슈가 러시 라이드'", "difficulty": 3 },
  { "id": "kb08", "category": "가요", "youtubeId": "iUw3LPM7OBU", "youtubeStart": 41, "youtubeEnd": 51, "hint": "라이즈의 펑키한 기타 리프", "answers": "'get a guitar', '겟 어 기타'", "difficulty": 2 },
  { "id": "kb09", "category": "가요", "youtubeId": "0TAAUWHo4Ec", "youtubeStart": 57, "youtubeEnd": 67, "hint": "라이즈의 첫사랑 기억 조작 곡", "answers": "'love 119', '러브 119'", "difficulty": 2 },
  { "id": "kb10", "category": "가요", "youtubeId": "hVAc1Vf2ITU", "youtubeStart": 44, "youtubeEnd": 54, "hint": "첫 만남은 너무 어려워~ (TWS)", "answers": "'첫 만남은 계획대로 되지 않아'", "difficulty": 1 },
  { "id": "kb11", "category": "가요", "youtubeId": "FxB6_qaqHlY", "youtubeStart": 48, "youtubeEnd": 58, "hint": "플레이브의 버추얼 히트곡", "answers": "'way 4 luv', '웨이 포 러브'", "difficulty": 3 },
  { "id": "kb12", "category": "가요", "youtubeId": "BS7tz2rAOSA", "youtubeStart": 63, "youtubeEnd": 73, "hint": "데이식스의 전설적인 벚꽃 연금곡", "answers": "'예뻤어'", "difficulty": 1 },
  { "id": "kb13", "category": "가요", "youtubeId": "vnS_jn2uibs", "youtubeStart": 66, "youtubeEnd": 76, "hint": "데이식스의 청춘 만화 같은 곡", "answers": "'한 페이지가 될 수 있게'", "difficulty": 1 },
  { "id": "kb14", "category": "가요", "youtubeId": "RowlrvmyFEk", "youtubeStart": 51, "youtubeEnd": 61, "hint": "이것이 우리만의 쇼~ (데이식스 최신곡)", "answers": "'welcome to the show', '웰컴 투 더 쇼'", "difficulty": 2 },
  { "id": "kb15", "category": "가요", "youtubeId": "ImuWa3SJulY", "youtubeStart": 58, "youtubeEnd": 68, "hint": "유튜버 김계란이 만든 걸밴드의 역주행 신화", "answers": "'고민중독'", "difficulty": 1 },
  { "id": "ks01", "category": "가요", "youtubeId": "xfqBQ2XhBCg", "youtubeStart": 49, "youtubeEnd": 59, "hint": "지코와 제니의 콜라보", "answers": "'spot', '스팟'", "difficulty": 1 },
  { "id": "ks02", "category": "가요", "youtubeId": "C_cpDd0WYTk", "youtubeStart": 41, "youtubeEnd": 51, "hint": "스우파 리더즈가 췄던 지코의 노래", "answers": "'새삥'", "difficulty": 2 },
  { "id": "ks03", "category": "가요", "youtubeId": "EIz09kLzN9k", "youtubeStart": 52, "youtubeEnd": 62, "hint": "악뮤의 큐피드 화살", "answers": "'love lee', '러브리', '러블리'", "difficulty": 1 },
  { "id": "ks04", "category": "가요", "youtubeId": "wAjOqRl1XpE", "youtubeStart": 61, "youtubeEnd": 71, "hint": "거위도 아니고 타조도 아니고", "answers": "'후라이의 꿈'", "difficulty": 2 },
  { "id": "ks05", "category": "가요", "youtubeId": "JleoAppaxi0", "youtubeStart": 57, "youtubeEnd": 67, "hint": "아이유와 뷔가 출연한 디스토피아 뮤비", "answers": "'love wins all', '러브 윈즈 올'", "difficulty": 1 },
  { "id": "ks06", "category": "가요", "youtubeId": "mFbILexYSQg", "youtubeStart": 46, "youtubeEnd": 56, "hint": "아이유의 신나는 홀씨", "answers": "'홀씨'", "difficulty": 2 },
  { "id": "ks07", "category": "가요", "youtubeId": "5_n6t9G2TUQ", "youtubeStart": 54, "youtubeEnd": 64, "hint": "태연의 감성적인 이별 노래", "answers": "'to x', '투 엑스'", "difficulty": 2 },
  { "id": "ks08", "category": "가요", "youtubeId": "Crq_fRV0O0E", "youtubeStart": 43, "youtubeEnd": 53, "hint": "아이 러브 마이 바디~ (화사)", "answers": "'i love my body', '아이 러브 마이 바디'", "difficulty": 2 },
  { "id": "ks09", "category": "가요", "youtubeId": "11iZcYbq_is", "youtubeStart": 49, "youtubeEnd": 59, "hint": "이영지와 도경수의 간질간질한 듀엣", "answers": "'small girl', '스몰 걸'", "difficulty": 1 },
  { "id": "ks10", "category": "가요", "youtubeId": "LKQ-18LoFQk", "youtubeStart": 68, "youtubeEnd": 78, "hint": "임영웅의 감성 발라드 최고봉", "answers": "'사랑은 늘 도망가'", "difficulty": 1 },
  { "id": "ks11", "category": "가요", "youtubeId": "yFlxYHjHYAw", "youtubeStart": 60, "youtubeEnd": 70, "hint": "박재정의 폭발적인 고음 발라드", "answers": "'헤어지자 말해요'", "difficulty": 1 },
  { "id": "ks12", "category": "가요", "youtubeId": "BBdC1rl5sKY", "youtubeStart": 64, "youtubeEnd": 74, "hint": "윤하의 역주행 천문학 노래", "answers": "'사건의 지평선'", "difficulty": 1 },
  { "id": "ks13", "category": "가요", "youtubeId": "smdmEhkIRVc", "youtubeStart": 35, "youtubeEnd": 45, "hint": "달디달고 달디달고 달디단~", "answers": "'밤양갱'", "difficulty": 1 },
  { "id": "ks14", "category": "가요", "youtubeId": "PVIf531Dt8E", "youtubeStart": 58, "youtubeEnd": 68, "hint": "이무진의 서정적인 고백송", "answers": "'에피소드', 'episode'", "difficulty": 2 },
  { "id": "ks15", "category": "가요", "youtubeId": "7ihLv8_Vd-4", "youtubeStart": 60, "youtubeEnd": 70, "hint": "최유리의 감성 인디 역주행 곡", "answers": "'숲'", "difficulty": 3 },
  { "id": "vm01", "category": "가요", "youtubeId": "ekr2nIex040", "youtubeStart": 42, "youtubeEnd": 52, "hint": "2024년 최고의 메가 히트 콜라보 (로제 & 브루노 마스)", "answers": "'apt', '아파트'", "difficulty": 1 },
  { "id": "vm04", "category": "가요", "youtubeId": "LuvJLjB8nBw", "youtubeStart": 60, "youtubeEnd": 70, "hint": "T의 성향을 묻는 인디 밈 곡", "answers": "'티라미수 케익', '티라미수케익'", "difficulty": 1 },
  { "id": "w001", "category": "팝송", "youtubeId": "JGwWNGJdvx8", "youtubeStart": 46, "youtubeEnd": 56, "hint": "Ed Sheeran의 전 세계 1위 곡", "answers": "'shape of you'", "difficulty": 1 },
  { "id": "w002", "category": "팝송", "youtubeId": "4NRXx6U8ABQ", "youtubeStart": 58, "youtubeEnd": 68, "hint": "80년대 신스팝 느낌의 더 위켄드 곡", "answers": "'blinding lights', '블라인딩 라이츠'", "difficulty": 1 },
  { "id": "w003", "category": "팝송", "youtubeId": "34Na4j8AVgA", "youtubeStart": 35, "youtubeEnd": 45, "hint": "다프트 펑크와 함께한 더 위켄드 곡", "answers": "'starboy', '스타보이'", "difficulty": 2 },
  { "id": "w004", "category": "팝송", "youtubeId": "nYh-n7EOtMA", "youtubeStart": 50, "youtubeEnd": 60, "hint": "Sia의 돈 없어도 즐거운 노래", "answers": "'cheap thrills', '칩 스릴스'", "difficulty": 1 },
  { "id": "w005", "category": "팝송", "youtubeId": "H5v3kku4y6Q", "youtubeStart": 45, "youtubeEnd": 55, "hint": "해리 스타일스의 솔로 대표곡", "answers": "'as it was'", "difficulty": 1 },
  { "id": "w006", "category": "팝송", "youtubeId": "ZmDBbnmKpqQ", "youtubeStart": 60, "youtubeEnd": 70, "hint": "올리비아 로드리고의 데뷔 싱글", "answers": "'drivers license', '드라이버스 라이센스'", "difficulty": 2 },
  { "id": "w007", "category": "팝송", "youtubeId": "rYEDA3JcQqw", "youtubeStart": 65, "youtubeEnd": 75, "hint": "아델의 복수심 가득한 노래", "answers": "'rolling in the deep', '롤링 인 더 딥'", "difficulty": 1 },
  { "id": "w008", "category": "팝송", "youtubeId": "gl1aHhXnN1k", "youtubeStart": 55, "youtubeEnd": 65, "hint": "전 남자친구들에게 감사하는 노래", "answers": "'thank u next', 'thank you next'", "difficulty": 1 },
  { "id": "w010", "category": "팝송", "youtubeId": "DyDfgMOUjCI", "youtubeStart": 72, "youtubeEnd": 82, "hint": "빌리 아일리시의 duh~", "answers": "'bad guy', '배드 가이'", "difficulty": 1 },
  { "id": "w011", "category": "팝송", "youtubeId": "VbfpW0pbvaU", "youtubeStart": 50, "youtubeEnd": 60, "hint": "숀 멘데스의 상처 노래", "answers": "'stitches', '스티치스'", "difficulty": 2 },
  { "id": "w012", "category": "팝송", "youtubeId": "fRh_vgS2dFE", "youtubeStart": 55, "youtubeEnd": 65, "hint": "저스틴 비버의 미안하다는 노래", "answers": "'sorry'", "difficulty": 1 },
  { "id": "w013", "category": "팝송", "youtubeId": "PT2_F-1esPk", "youtubeStart": 65, "youtubeEnd": 75, "hint": "체인스모커스 X 홀지", "answers": "'closer', '클로저'", "difficulty": 2 },
  { "id": "w014", "category": "팝송", "youtubeId": "TUVcZfQe-Kw", "youtubeStart": 50, "youtubeEnd": 60, "hint": "두아 리파의 우주적인 노래", "answers": "'levitating', '레비테이팅'", "difficulty": 1 },
  { "id": "w015", "category": "팝송", "youtubeId": "OPf0YbXqDm0", "youtubeStart": 58, "youtubeEnd": 68, "hint": "브루노 마스의 업타운 펑크", "answers": "'uptown funk', '업타운 펑크'", "difficulty": 1 },
  { "id": "wp01", "category": "팝송", "youtubeId": "Oa_RSwwpPaA", "youtubeStart": 53, "youtubeEnd": 63, "hint": "Please stay~ 벤슨 분의 틱톡 떡상 곡", "answers": "'beautiful things', '뷰티풀 띵스'", "difficulty": 1 },
  { "id": "wp02", "category": "팝송", "youtubeId": "GZ3zL7kT6_c", "youtubeStart": 47, "youtubeEnd": 57, "hint": "테디 스윔스의 거친 소울 히트곡", "answers": "'lose control', '루즈 컨트롤'", "difficulty": 2 },
  { "id": "wp03", "category": "팝송", "youtubeId": "eVli-tstM5E", "youtubeStart": 36, "youtubeEnd": 46, "hint": "사브리나 카펜터의 카페인 같은 노래", "answers": "'espresso', '에스프레소'", "difficulty": 1 },
  { "id": "wp04", "category": "팝송", "youtubeId": "cF1Na4AIecM", "youtubeStart": 49, "youtubeEnd": 59, "hint": "제발 날 울리지 마 (Sabrina Carpenter)", "answers": "'please please please', '플리즈 플리즈 플리즈'", "difficulty": 2 },
  { "id": "wp05", "category": "팝송", "youtubeId": "ic8j13piAhQ", "youtubeStart": 62, "youtubeEnd": 72, "hint": "테일러 스위프트의 잔인한 여름", "answers": "'cruel summer', '크루엘 섬머'", "difficulty": 1 },
  { "id": "wp07", "category": "팝송", "youtubeId": "Mx92lTYxrJQ", "youtubeStart": 50, "youtubeEnd": 60, "hint": "더 위켄드와 제니의 아찔한 콜라보", "answers": "'one of the girls', '원 오브 더 걸스'", "difficulty": 2 },
  { "id": "wp08", "category": "팝송", "youtubeId": "KNtJGQkC-WI", "youtubeStart": 41, "youtubeEnd": 51, "hint": "아리아나 그란데의 \"우리는 친구가 될 수 없어\"", "answers": "\"we can't be friends\", 'we cant be friends'", "difficulty": 1 },
  { "id": "wp09", "category": "팝송", "youtubeId": "cW8VLC9nnTo", "youtubeStart": 74, "youtubeEnd": 84, "hint": "빌리 아일리시의 바비 OST", "answers": "'what was i made for'", "difficulty": 2 },
  { "id": "wp10", "category": "팝송", "youtubeId": "V9PVRfjEBTI", "youtubeStart": 51, "youtubeEnd": 61, "hint": "빌리 아일리시의 새가 된 듯한 곡", "answers": "'birds of a feather', '버즈 오브 어 페더'", "difficulty": 2 },
  { "id": "wp11", "category": "팝송", "youtubeId": "suAR1PYFNYA", "youtubeStart": 45, "youtubeEnd": 55, "hint": "두아 리파의 Catch me or I go", "answers": "'houdini', '후디니'", "difficulty": 2 },
  { "id": "wp12", "category": "팝송", "youtubeId": "OiC1rgCPmUQ", "youtubeStart": 39, "youtubeEnd": 49, "hint": "두아 리파의 신나는 댄스 넘버", "answers": "'dance the night', '댄스 더 나이트'", "difficulty": 2 },
  { "id": "wp13", "category": "팝송", "youtubeId": "m4_9TFeMfJE", "youtubeStart": 56, "youtubeEnd": 66, "hint": "도자 캣의 붉게 물들여", "answers": "'paint the town red'", "difficulty": 2 },
  { "id": "wp14", "category": "팝송", "youtubeId": "XoiOOiuH8iI", "youtubeStart": 37, "youtubeEnd": 47, "hint": "타일라의 관능적인 아프로비츠 곡", "answers": "'water', '워터'", "difficulty": 1 },
  { "id": "wp15", "category": "팝송", "youtubeId": "RlPNh_PBZb4", "youtubeStart": 59, "youtubeEnd": 69, "hint": "올리비아 로드리고의 뱀파이어", "answers": "'vampire', '뱀파이어'", "difficulty": 1 },
  { "id": "wp16", "category": "팝송", "youtubeId": "gNi_6U5Pm_o", "youtubeStart": 43, "youtubeEnd": 53, "hint": "올리비아 로드리고의 펑크 록 하이틴", "answers": "'good 4 u', 'good for you'", "difficulty": 2 },
  { "id": "wp17", "category": "팝송", "youtubeId": "H5v3kku4y6Q", "youtubeStart": 49, "youtubeEnd": 59, "hint": "해리 스타일스의 감각적인 솔로곡", "answers": "'as it was'", "difficulty": 1 },
  { "id": "wp18", "category": "팝송", "youtubeId": "b53QJYP-lqY", "youtubeStart": 52, "youtubeEnd": 62, "hint": "트로이 시반의 신나는 클럽 트랙", "answers": "'rush', '러시'", "difficulty": 2 },
  { "id": "wp19", "category": "팝송", "youtubeId": "a7GITgqwDVg", "youtubeStart": 44, "youtubeEnd": 54, "hint": "찰리 푸스와 정국의 좌우 음향 곡", "answers": "'left and right', '레프트 앤 라이트'", "difficulty": 1 },
  { "id": "wp20", "category": "팝송", "youtubeId": "TBXQu8ORnBQ", "youtubeStart": 63, "youtubeEnd": 73, "hint": "한국에서 역주행한 찰리 푸스 명곡", "answers": "'dangerously', '데인저러스리'", "difficulty": 2 },
  { "id": "wp21", "category": "팝송", "youtubeId": "G7KNmW9a75Y", "youtubeStart": 46, "youtubeEnd": 56, "hint": "마일리 사이러스의 당당한 1위 곡", "answers": "'flowers', '플라워스'", "difficulty": 1 },
  { "id": "wp22", "category": "팝송", "youtubeId": "MSRcC626prw", "youtubeStart": 57, "youtubeEnd": 67, "hint": "SZA의 전 남친 저격 노래", "answers": "'kill bill', '킬 빌'", "difficulty": 2 },
  { "id": "wp23", "category": "팝송", "youtubeId": "oftolPu9qp4", "youtubeStart": 35, "youtubeEnd": 45, "hint": "핑크팬서레스의 틱톡 화제곡", "answers": "\"boy's a liar\", 'boys a liar'", "difficulty": 3 },
  { "id": "wp24", "category": "팝송", "youtubeId": "kTJczUoc26U", "youtubeStart": 41, "youtubeEnd": 51, "hint": "더 키드 라로이 & 저스틴 비버", "answers": "'stay', '스테이'", "difficulty": 1 },
  { "id": "wp25", "category": "팝송", "youtubeId": "Uq9gPaIzbe8", "youtubeStart": 52, "youtubeEnd": 62, "hint": "샘 스미스의 불경한(?) 댄스곡", "answers": "'unholy', '언홀리'", "difficulty": 1 },
  { "id": "wp26", "category": "팝송", "youtubeId": "GxldQ9eX2wo", "youtubeStart": 63, "youtubeEnd": 73, "hint": "스티븐 산체스의 복고풍 로맨스", "answers": "'until i found you', '언틸 아이 파운드 유'", "difficulty": 3 },
  { "id": "wp27", "category": "팝송", "youtubeId": "adLGHcj_fmA", "youtubeStart": 58, "youtubeEnd": 68, "hint": "브루노 마스의 실크 소닉 문 열어둬", "answers": "'leave the door open', '리브 더 도어 오픈'", "difficulty": 2 },
  { "id": "wp28", "category": "팝송", "youtubeId": "Il0S8BoucSA", "youtubeStart": 49, "youtubeEnd": 59, "hint": "에드 시런의 몸이 떨리는 노래", "answers": "'shivers', '시버스'", "difficulty": 2 },
  { "id": "wp29", "category": "팝송", "youtubeId": "PEM0Vs8jf1w", "youtubeStart": 61, "youtubeEnd": 71, "hint": "JVKE의 아름다운 황금빛 피아노", "answers": "'golden hour', '골든 아워'", "difficulty": 2 },
  { "id": "wp30", "category": "팝송", "youtubeId": "uPD0QOGTmMI", "youtubeStart": 48, "youtubeEnd": 58, "hint": "더 위켄드의 틱톡 역주행 명곡", "answers": "'die for you', '다이 포 유'", "difficulty": 2 },
  { "id": "m001", "category": "영화", "youtubeId": "GT-SfFbFGsY", "youtubeStart": 20, "youtubeEnd": 30, "hint": "2019 칸 영화제 황금종려상 수상 영화", "answers": "'기생충', 'parasite'", "difficulty": 2 },
  { "id": "m002", "category": "영화", "youtubeId": "2uMX_opOvDI", "youtubeStart": 60, "youtubeEnd": 70, "hint": "첫사랑을 다룬 로맨스 영화", "answers": "'건축학개론', 'architecture 101'", "difficulty": 3 },
  { "id": "m003", "category": "영화", "youtubeId": "FOLccTgFJz8", "youtubeStart": 18, "youtubeEnd": 28, "hint": "80년대 여고생들의 우정 이야기", "answers": "'써니', 'sunny'", "difficulty": 2 },
  { "id": "m004", "category": "영화", "youtubeId": "5O5PVvHTWRo", "youtubeStart": 0, "youtubeEnd": 10, "hint": "저승 삼차사와 함께하는 심판 이야기", "answers": "'신과 함께', '신과함께', 'along with the gods'", "difficulty": 2 },
  { "id": "m005", "category": "영화", "youtubeId": "xM1CIQd_X4c", "youtubeStart": 0, "youtubeEnd": 10, "hint": "치킨집을 운영하는 마약반 형사들", "answers": "'극한직업', 'extreme job'", "difficulty": 3 },
  { "id": "a003", "category": "영화", "youtubeId": "m3zvVGJrTP8", "youtubeStart": 120, "youtubeEnd": 130, "hint": "크리스토퍼 놀란 감독의 우주 영화", "answers": "'인터스텔라', 'interstellar'", "difficulty": 2 },
  { "id": "a006", "category": "영화", "youtubeId": "fJ9rUzIMcZQ", "youtubeStart": 45, "youtubeEnd": 55, "hint": "퀸의 전기 영화", "answers": "'보헤미안 랩소디', 'bohemian rhapsody'", "difficulty": 1 },
  { "id": "a007", "category": "영화", "youtubeId": "FOabQZHT4qY", "youtubeStart": 60, "youtubeEnd": 70, "hint": "마블 히어로들의 집합", "answers": "'어벤져스', 'avengers'", "difficulty": 1 },
  { "id": "a008", "category": "영화", "youtubeId": "cZAw8qxn0ZE", "youtubeStart": 50, "youtubeEnd": 60, "hint": "재즈 피아니스트와 배우 지망생의 사랑", "answers": "'라라랜드', 'la la land', 'city of stars'", "difficulty": 2 },
  { "id": "a009", "category": "영화", "youtubeId": "Imu4CmE6Nmg", "youtubeStart": 5, "youtubeEnd": 15, "hint": "거미줄을 타는 히어로", "answers": "'스파이더맨', 'spider-man', 'spiderman'", "difficulty": 1 },
  { "id": "a010", "category": "영화", "youtubeId": "yK0P1Bk8Cx4", "youtubeStart": 50, "youtubeEnd": 60, "hint": "전투기 파일럿의 이야기, 2022년 속편", "answers": "'탑건', 'top gun', '탑건 매버릭', 'top gun maverick'", "difficulty": 2 },
  { "id": "a001", "category": "애니메이션", "youtubeId": "L0MK7qz13bU", "youtubeStart": 60, "youtubeEnd": 70, "hint": "눈의 여왕이 부르는 노래", "answers": "'렛잇고', 'let it go', '겨울왕국', 'frozen'", "difficulty": 1 },
  { "id": "a002", "category": "애니메이션", "youtubeId": "GibiNy4d4gc", "youtubeStart": 25, "youtubeEnd": 35, "hint": "아프리카 초원의 왕 이야기", "answers": "'라이온킹', 'lion king', 'circle of life'", "difficulty": 1 },
  { "id": "a004", "category": "애니메이션", "youtubeId": "1MPZRcyTrcU", "youtubeStart": 7, "youtubeEnd": 17, "hint": "장난감들의 우정 이야기", "answers": "'토이스토리', 'toy story', \"you've got a friend in me\"", "difficulty": 1 },
  { "id": "a005", "category": "애니메이션", "youtubeId": "WUiI5aQcTow", "youtubeStart": 0, "youtubeEnd": 10, "hint": "마법사 학교 호그와트 이야기", "answers": "'해리포터', 'harry potter', 'hedwigs theme'", "difficulty": 1 },
  { "id": "an001", "category": "애니메이션", "youtubeId": "0OdExTY2D8M", "youtubeStart": 33, "youtubeEnd": 43, "hint": "해적왕이 되겠다 루피의 모험", "answers": "'원피스', 'one piece'", "difficulty": 1 },
  { "id": "an002", "category": "애니메이션", "youtubeId": "E_BsL8_cFnE", "youtubeStart": 33, "youtubeEnd": 43, "hint": "피카츄 포켓몬 마스터", "answers": "'포켓몬스터', '포켓몬', 'pokemon'", "difficulty": 1 },
  { "id": "an003", "category": "애니메이션", "youtubeId": "kmrONTZnKo0", "youtubeStart": 52, "youtubeEnd": 62, "hint": "목숨을 건 결투 유희왕", "answers": "'유희왕', 'yu-gi-oh'", "difficulty": 1 },
  { "id": "an004", "category": "애니메이션", "youtubeId": "AE4b9jO1uB4", "youtubeStart": 54, "youtubeEnd": 64, "hint": "닌자 나루토와 동료들의 이야기", "answers": "'나루토', 'naruto'", "difficulty": 1 },
  { "id": "an005", "category": "애니메이션", "youtubeId": "3RVsOcufd9k", "youtubeStart": 42, "youtubeEnd": 52, "hint": "강철의 연금술사 에드워드", "answers": "'강철의 연금술사', '풀메탈 알케미스트', 'fullmetal alchemist'", "difficulty": 1 },
  { "id": "an006", "category": "애니메이션", "youtubeId": "o6wtDPVkKqI", "youtubeStart": 48, "youtubeEnd": 58, "hint": "총을 쏘며 활약하는 에바", "answers": "'신세기 에반게리온', '에바', 'evangelion'", "difficulty": 2 },
  { "id": "an007", "category": "애니메이션", "youtubeId": "Uku3t8qAloc", "youtubeStart": 60, "youtubeEnd": 70, "hint": "귀신을 베는 탄지로의 이야기", "answers": "'귀멸의 칼날', '기멸의 칼날', 'demon slayer', 'kimetsu no yaiba'", "difficulty": 1 },
  { "id": "an008", "category": "애니메이션", "youtubeId": "CID-sYQNCew", "youtubeStart": 60, "youtubeEnd": 70, "hint": "거인을 향해 싸우는 에렌", "answers": "'진격의 거인', 'attack on titan'", "difficulty": 1 },
  { "id": "an009", "category": "애니메이션", "youtubeId": "CbH2F0kXgTY", "youtubeStart": 60, "youtubeEnd": 70, "hint": "스파이 가족 로이드와 아냐", "answers": "'스파이 패밀리', 'spy x family'", "difficulty": 1 },
  { "id": "an010", "category": "애니메이션", "youtubeId": "1tk1pqwrOys", "youtubeStart": 54, "youtubeEnd": 64, "hint": "주술을 부리는 이타도리 유지", "answers": "'주술회전', 'jujutsu kaisen'", "difficulty": 1 },
  { "id": "an011", "category": "애니메이션", "youtubeId": "Th7MAZYFIMc", "youtubeStart": 52, "youtubeEnd": 62, "hint": "히로아카 데쿠의 영웅 이야기", "answers": "'나의 히어로 아카데미아', '히로아카', 'my hero academia'", "difficulty": 1 },
  { "id": "an012", "category": "애니메이션", "youtubeId": "c33MnfP0Gfs", "youtubeStart": 41, "youtubeEnd": 51, "hint": "이웃집 토토로 메이와 사츠키", "answers": "'이웃집 토토로', '토토로', 'my neighbor totoro'", "difficulty": 1 },
  { "id": "an013", "category": "애니메이션", "youtubeId": "gtOks_p85_w", "youtubeStart": 55, "youtubeEnd": 65, "hint": "센과 치히로의 행방불명", "answers": "'센과 치히로', 'spirited away'", "difficulty": 1 },
  { "id": "an014", "category": "애니메이션", "youtubeId": "XjBSzdoVVZE", "youtubeStart": 30, "youtubeEnd": 40, "hint": "원령공주 아시타카와 모노노케", "answers": "'원령공주', 'princess mononoke'", "difficulty": 2 },
  { "id": "an015", "category": "애니메이션", "youtubeId": "Hnt32LNVALk", "youtubeStart": 8, "youtubeEnd": 18, "hint": "하울의 움직이는 성", "answers": "'하울의 움직이는 성', \"howl's moving castle\"", "difficulty": 1 },
  { "id": "an016", "category": "애니메이션", "youtubeId": "s4pgnGqkNEU", "youtubeStart": 30, "youtubeEnd": 40, "hint": "미래의 도라에몽 로봇 고양이", "answers": "'도라에몽', 'doraemon'", "difficulty": 1 },
  { "id": "an017", "category": "애니메이션", "youtubeId": "DBEYpGEsOHs", "youtubeStart": 18, "youtubeEnd": 28, "hint": "짱구는 못말려 노하라 신노스케", "answers": "'짱구는 못말려', '크레용 신짱', 'crayon shinchan'", "difficulty": 1 },
  { "id": "an018", "category": "애니메이션", "youtubeId": "mgWONfthS9U", "youtubeStart": 60, "youtubeEnd": 70, "hint": "슬램덩크 강백호의 농구", "answers": "'슬램덩크', 'slam dunk'", "difficulty": 1 },
  { "id": "an019", "category": "애니메이션", "youtubeId": "fGbWJ0YPEH8", "youtubeStart": 50, "youtubeEnd": 60, "hint": "드래곤볼 손오공의 싸움", "answers": "'드래곤볼', 'dragon ball'", "difficulty": 1 },
  { "id": "an020", "category": "애니메이션", "youtubeId": "wW9TwZdWpjw", "youtubeStart": 30, "youtubeEnd": 40, "hint": "블리치 이치고의 사신", "answers": "'블리치', 'bleach'", "difficulty": 2 },
  { "id": "an021", "category": "애니메이션", "youtubeId": "AOqLEZoGpNw", "youtubeStart": 40, "youtubeEnd": 50, "hint": "명탐정 코난 에도가와 코난", "answers": "'명탐정 코난', '코난', 'detective conan'", "difficulty": 1 },
  { "id": "an022", "category": "애니메이션", "youtubeId": "6KYk5a93OC8", "youtubeStart": 60, "youtubeEnd": 70, "hint": "세일러문 마법소녀", "answers": "'미소녀전사 세일러문', '세일러문', 'sailor moon'", "difficulty": 1 },
  { "id": "an023", "category": "애니메이션", "youtubeId": "6gpcPYDkPdg", "youtubeStart": 42, "youtubeEnd": 52, "hint": "카드캡터 사쿠라 마법 카드", "answers": "'카드캡터 사쿠라', 'cardcaptor sakura'", "difficulty": 2 },
  { "id": "an024", "category": "애니메이션", "youtubeId": "ktcKUrIW2iw", "youtubeStart": 30, "youtubeEnd": 40, "hint": "요괴워치 지바냥", "answers": "'요괴워치', 'yokai watch'", "difficulty": 1 },
  { "id": "an025", "category": "애니메이션", "youtubeId": "oZU6QvWHBxY", "youtubeStart": 38, "youtubeEnd": 48, "hint": "원펀맨 사이타마 한 방으로 끝", "answers": "'원펀맨', 'one punch man'", "difficulty": 1 },
  { "id": "cl001", "category": "클래식 음악", "youtubeId": "OV6Lp7cnX7s", "youtubeStart": 0, "youtubeEnd": 10, "hint": "빠바바밤~ 베토벤의 운명", "answers": "'운명 교향곡', '베토벤 5번', '운명'", "difficulty": 1 },
  { "id": "cl002", "category": "클래식 음악", "youtubeId": "GRxofEmo3HA", "youtubeStart": 5, "youtubeEnd": 15, "hint": "비발디의 봄 1악장", "answers": "'사계', '비발디 사계', '봄'", "difficulty": 1 },
  { "id": "cl003", "category": "클래식 음악", "youtubeId": "gFjveJ5sgeQ", "youtubeStart": 6, "youtubeEnd": 16, "hint": "차이콥스키의 호두까기 인형 중 사탕요정의 춤", "answers": "'호두까기 인형', '사탕요정의 춤', 'nutcracker'", "difficulty": 1 },
  { "id": "cl004", "category": "클래식 음악", "youtubeId": "2uvMgL4m2Cc", "youtubeStart": 8, "youtubeEnd": 18, "hint": "엘가의 위풍당당 행진곡", "answers": "'위풍당당 행진곡', '엘가', 'pomp and circumstance'", "difficulty": 1 },
  { "id": "cl005", "category": "클래식 음악", "youtubeId": "cJ6gIPLxJ5w", "youtubeStart": 0, "youtubeEnd": 10, "hint": "모차르트의 아이네 클라이네 나흐트무지크", "answers": "'아이네 클라이네', '모차르트 세레나데', 'eine kleine nachtmusik'", "difficulty": 2 },
  { "id": "cl006", "category": "클래식 음악", "youtubeId": "XWOC6xImhtg", "youtubeStart": 8, "youtubeEnd": 18, "hint": "바흐의 G선상의 아리아", "answers": "'G선상의 아리아', '바흐 아리아', 'air on g string'", "difficulty": 2 },
  { "id": "cl007", "category": "클래식 음악", "youtubeId": "jOofzffyDSA", "youtubeStart": 60, "youtubeEnd": 70, "hint": "드보르작 신세계 교향곡 4악장", "answers": "'신세계 교향곡', '드보르작 신세계', 'new world symphony'", "difficulty": 2 },
  { "id": "cl008", "category": "클래식 음악", "youtubeId": "RIck7OCm6UU", "youtubeStart": 0, "youtubeEnd": 10, "hint": "차이콥스키 백조의 호수 테마", "answers": "'백조의 호수', 'swan lake'", "difficulty": 1 },
  { "id": "cl009", "category": "클래식 음악", "youtubeId": "YGRO05WcNDk", "youtubeStart": 5, "youtubeEnd": 15, "hint": "쇼팽의 야상곡(녹턴)", "answers": "'녹턴', '야상곡', 'nocturne'", "difficulty": 2 },
  { "id": "cl010", "category": "클래식 음악", "youtubeId": "4LLylhgR3uM", "youtubeStart": 5, "youtubeEnd": 15, "hint": "라벨의 볼레로", "answers": "'볼레로', 'bolero'", "difficulty": 1 },
  { "id": "cl011", "category": "클래식 음악", "youtubeId": "4Tr0otuiQuU", "youtubeStart": 0, "youtubeEnd": 10, "hint": "베토벤 월광 소나타 1악장", "answers": "'월광 소나타', '월광', 'moonlight sonata'", "difficulty": 1 },
  { "id": "cl012", "category": "클래식 음악", "youtubeId": "IUZEtVbJT5c", "youtubeStart": 20, "youtubeEnd": 30, "hint": "헨델의 메시아 중 할렐루야", "answers": "'할렐루야', 'hallelujah', '헨델 할렐루야'", "difficulty": 1 },
  { "id": "cl013", "category": "클래식 음악", "youtubeId": "Gus4dnQuiGk", "youtubeStart": 0, "youtubeEnd": 10, "hint": "쇼팽 즉흥 환상곡", "answers": "'환상 즉흥곡', '즉흥환상곡', 'fantasie impromptu'", "difficulty": 2 },
  { "id": "cl014", "category": "클래식 음악", "youtubeId": "wfF0zHeU3Zs", "youtubeStart": 0, "youtubeEnd": 10, "hint": "베토벤 엘리제를 위하여", "answers": "'엘리제를 위하여', 'fur elise'", "difficulty": 1 },
  { "id": "cl015", "category": "클래식 음악", "youtubeId": "hsBt9yZDslA", "youtubeStart": 12, "youtubeEnd": 22, "hint": "슈베르트 아베 마리아", "answers": "'아베 마리아', 'ave maria'", "difficulty": 1 },
  { "id": "cl016", "category": "클래식 음악", "youtubeId": "zWytgJy-u8w", "youtubeStart": 30, "youtubeEnd": 40, "hint": "오펜바흐 캉캉", "answers": "'캉캉', 'can can', '오펜바흐'", "difficulty": 1 },
  { "id": "cl017", "category": "클래식 음악", "youtubeId": "JNbe34V1nog", "youtubeStart": 28, "youtubeEnd": 38, "hint": "파헬벨의 캐논", "answers": "'캐논', 'canon', '캐논변주곡'", "difficulty": 1 },
  { "id": "cl018", "category": "클래식 음악", "youtubeId": "fiOGCwZGgXY", "youtubeStart": 60, "youtubeEnd": 70, "hint": "스메타나 나의 조국 중 몰다우", "answers": "'몰다우', 'moldau', '나의조국'", "difficulty": 2 },
  { "id": "cl019", "category": "클래식 음악", "youtubeId": "NegCKtoRfR8", "youtubeStart": 6, "youtubeEnd": 16, "hint": "생상스 동물의 사육제 중 백조", "answers": "'동물의 사육제', '백조', 'carnival of the animals'", "difficulty": 2 },
  { "id": "cl020", "category": "클래식 음악", "youtubeId": "jxa2er9Y1iU", "youtubeStart": 0, "youtubeEnd": 10, "hint": "무소르그스키 전람회의 그림", "answers": "'전람회의 그림', 'pictures at an exhibition'", "difficulty": 3 },
  { "id": "cp001", "category": "작곡가", "youtubeId": "OV6Lp7cnX7s", "youtubeStart": 0, "youtubeEnd": 10, "hint": "운명 교향곡, 월광 소나타를 작곡한 독일 작곡가", "answers": "'베토벤', 'beethoven', '루트비히 반 베토벤'", "difficulty": 1 },
  { "id": "cp002", "category": "작곡가", "youtubeId": "Qb_jQBgzU-I", "youtubeStart": 0, "youtubeEnd": 10, "hint": "피가로의 결혼, 마술피리를 작곡한 신동", "answers": "'모차르트', 'mozart', '볼프강 아마데우스 모차르트'", "difficulty": 1 },
  { "id": "cp003", "category": "작곡가", "youtubeId": "GRxofEmo3HA", "youtubeStart": 5, "youtubeEnd": 15, "hint": "사계를 작곡한 이탈리아 바로크 작곡가", "answers": "'비발디', 'vivaldi', '안토니오 비발디'", "difficulty": 1 },
  { "id": "cp004", "category": "작곡가", "youtubeId": "8tpzyYFqJWM", "youtubeStart": 0, "youtubeEnd": 10, "hint": "G선상의 아리아, 토카타와 푸가를 작곡한 바로크 거장", "answers": "'바흐', 'bach', '요한 세바스티안 바흐'", "difficulty": 1 },
  { "id": "cp005", "category": "작곡가", "youtubeId": "192zr438g-k", "youtubeStart": 0, "youtubeEnd": 10, "hint": "환상 즉흥곡, 녹턴을 작곡한 피아노 시인", "answers": "'쇼팽', 'chopin', '프레데릭 쇼팽'", "difficulty": 1 },
  { "id": "cp006", "category": "작곡가", "youtubeId": "9cNQFB0TDfY", "youtubeStart": 0, "youtubeEnd": 10, "hint": "백조의 호수, 호두까기 인형을 작곡한 러시아 작곡가", "answers": "'차이콥스키', 'tchaikovsky', '표트르 차이콥스키'", "difficulty": 1 },
  { "id": "cp007", "category": "작곡가", "youtubeId": "0FbQZCsYXVg", "youtubeStart": 0, "youtubeEnd": 10, "hint": "헝가리 랩소디를 작곡한 피아노 거장", "answers": "'리스트', 'liszt', '프란츠 리스트'", "difficulty": 2 },
  { "id": "cp008", "category": "작곡가", "youtubeId": "5Eqj9G5j1ss", "youtubeStart": 0, "youtubeEnd": 10, "hint": "볼레로를 작곡한 프랑스 작곡가", "answers": "'라벨', 'ravel', '모리스 라벨'", "difficulty": 2 },
  { "id": "cp009", "category": "작곡가", "youtubeId": "L6P3cIJHWjw", "youtubeStart": 0, "youtubeEnd": 10, "hint": "교향시 핀란디아를 작곡한 핀란드 작곡가", "answers": "'시벨리우스', 'sibelius', '장 시벨리우스'", "difficulty": 3 },
  { "id": "cp010", "category": "작곡가", "youtubeId": "jF1OQkHybEQ", "youtubeStart": 30, "youtubeEnd": 40, "hint": "봄의 제전을 작곡한 현대 작곡가", "answers": "'스트라빈스키', 'stravinsky', '이고르 스트라빈스키'", "difficulty": 2 },
  { "id": "cp011", "category": "작곡가", "youtubeId": "XpYGgtrMTYs", "youtubeStart": 0, "youtubeEnd": 10, "hint": "미완성 교향곡을 작곡한 오스트리아 작곡가", "answers": "'슈베르트', 'schubert', '프란츠 슈베르트'", "difficulty": 2 },
  { "id": "cp012", "category": "작곡가", "youtubeId": "jOofzffyDSA", "youtubeStart": 60, "youtubeEnd": 70, "hint": "신세계 교향곡을 작곡한 체코 작곡가", "answers": "'드보르작', 'dvorak', '안토닌 드보르작'", "difficulty": 2 },
  { "id": "cp013", "category": "작곡가", "youtubeId": "K2snTkaD64U", "youtubeStart": 0, "youtubeEnd": 10, "hint": "카르멘을 작곡한 프랑스 오페라 작곡가", "answers": "'비제', 'bizet', '조르주 비제'", "difficulty": 2 },
  { "id": "cp014", "category": "작곡가", "youtubeId": "HqNa9Cpa3L8", "youtubeStart": 0, "youtubeEnd": 10, "hint": "아이다, 오텔로를 작곡한 이탈리아 오페라 작곡가", "answers": "'베르디', 'verdi', '주세페 베르디'", "difficulty": 2 },
  { "id": "cp015", "category": "작곡가", "youtubeId": "9ADfSxJ3AFE", "youtubeStart": 0, "youtubeEnd": 10, "hint": "라 트라비아타를 작곡한 이탈리아 작곡가", "answers": "'푸치니', 'puccini', '자코모 푸치니'", "difficulty": 2 },
  { "id": "pa001", "category": "공연 예술", "youtubeId": "GqrH1z8L-9Q", "youtubeStart": 156, "youtubeEnd": 166, "hint": "뮤지컬 캣츠의 대표곡 Memory", "answers": "'캣츠', 'cats', 'memory'", "difficulty": 1 },
  { "id": "pa002", "category": "공연 예술", "youtubeId": "8J1lmuchz7o", "youtubeStart": 73, "youtubeEnd": 83, "hint": "오페라의 유령 테마곡", "answers": "'오페라의 유령', 'phantom of the opera'", "difficulty": 1 },
  { "id": "pa003", "category": "공연 예술", "youtubeId": "Ojxmk78lMXY", "youtubeStart": 158, "youtubeEnd": 168, "hint": "뮤지컬 레 미제라블의 I Dreamed a Dream", "answers": "'레 미제라블', 'les miserables', '레미제라블'", "difficulty": 1 },
  { "id": "pa004", "category": "공연 예술", "youtubeId": "Do8oqR2TR1M", "youtubeStart": 50, "youtubeEnd": 60, "hint": "뮤지컬 맘마미아의 ABBA 노래", "answers": "'맘마미아', 'mamma mia', 'abba'", "difficulty": 1 },
  { "id": "pa005", "category": "공연 예술", "youtubeId": "GibiNy4d4gc", "youtubeStart": 10, "youtubeEnd": 20, "hint": "뮤지컬 라이온킹 Circle of Life", "answers": "'라이온킹', 'lion king', 'circle of life'", "difficulty": 1 },
  { "id": "pa006", "category": "공연 예술", "youtubeId": "l0Bs_eaXaCo", "youtubeStart": 200, "youtubeEnd": 210, "hint": "뮤지컬 위키드의 Defying Gravity", "answers": "'위키드', 'wicked', 'defying gravity'", "difficulty": 2 },
  { "id": "pa007", "category": "공연 예술", "youtubeId": "VhinPd5RRJw", "youtubeStart": 30, "youtubeEnd": 40, "hint": "뮤지컬 해밀턴의 Alexander Hamilton", "answers": "'해밀턴', 'hamilton'", "difficulty": 2 },
  { "id": "pa008", "category": "공연 예술", "youtubeId": "Le8a7u1pANU", "youtubeStart": 75, "youtubeEnd": 85, "hint": "뮤지컬 시카고의 All That Jazz", "answers": "'시카고', 'chicago', 'all that jazz'", "difficulty": 2 },
  { "id": "pa009", "category": "공연 예술", "youtubeId": "KJ_HHRJf0xg", "youtubeStart": 18, "youtubeEnd": 28, "hint": "오페라 카르멘의 하바네라", "answers": "'카르멘', 'carmen', '하바네라'", "difficulty": 2 },
  { "id": "pa010", "category": "공연 예술", "youtubeId": "SK-NUuTCras", "youtubeStart": 12, "youtubeEnd": 22, "hint": "오페라 라 트라비아타의 축배의 노래", "answers": "'라 트라비아타', 'la traviata', '축배의 노래'", "difficulty": 2 },
  { "id": "pa011", "category": "공연 예술", "youtubeId": "e__Pp4FxsjU", "youtubeStart": 65, "youtubeEnd": 75, "hint": "뮤지컬 그리스의 Summer Nights", "answers": "'그리스', 'grease', 'summer nights'", "difficulty": 1 },
  { "id": "pa012", "category": "공연 예술", "youtubeId": "Qy9cj-zwbVY", "youtubeStart": 60, "youtubeEnd": 70, "hint": "뮤지컬 사운드 오브 뮤직의 Do Re Mi", "answers": "'사운드 오브 뮤직', 'sound of music', 'do re mi'", "difficulty": 1 },
  { "id": "pa013", "category": "공연 예술", "youtubeId": "8woil4kgU5Y", "youtubeStart": 8, "youtubeEnd": 18, "hint": "발레 잠자는 숲속의 미녀 테마", "answers": "'잠자는 숲속의 미녀', 'sleeping beauty', '차이콥스키 발레'", "difficulty": 2 },
  { "id": "pa014", "category": "공연 예술", "youtubeId": "FVnxKAoFzBg", "youtubeStart": 14, "youtubeEnd": 24, "hint": "뮤지컬 노트르담 드 파리", "answers": "'노트르담 드 파리', 'notre dame de paris', '노트르담'", "difficulty": 2 },
  { "id": "pa015", "category": "공연 예술", "youtubeId": "rEREXwJ2P9Q", "youtubeStart": 70, "youtubeEnd": 80, "hint": "한국 뮤지컬 명성황후", "answers": "'명성황후', '명성황후 뮤지컬'", "difficulty": 2 }
];

module.exports = { RAW_QUIZ_DATA };
