// server/quizData.js
// ══════════════════════════════════════════════════════════════
// RAW_QUIZ_DATA
// ──────────────────────────────────────────────────────────────
// 카테고리별 문제 수 요약:
// 드라마 : 16개 (k001~k010, vm05~vm10)
// 가요 : 67개 (p001~p015, kg01~kg20, kb01~kb15, ks01~ks15, vm01, vm04)
// 팝송 : 45개 (w001~w015, wp01~wp30)
// 영화 : 10개 (m001~m005, a003, a006~a010)
// 애니메이션 : 29개 (a001~a002, a004~a005, an001~an025)
// 동요 : 30개 (dy001~dy030)
// 클래식 음악 : 20개 (cl001~cl020)
// 작곡가 : 15개 (cp001~cp015)
// 공연 예술 : 15개 (pa001~pa015)
// 스포츠 : 20개 (sp001~sp020)
// 운송수단 : 20개 (tr001~tr020)
// 악기 : 25개 (in001~in025)
// 동물 : 25개 (an101~an125)
// 계절 : 10개 (se001~se010)
// 자연현상 : 15개 (nt001~nt015)
// 불쾌한 소리 : 15개 (ug001~ug015)
// 직업 : 15개 (jb001~jb015)
// 물건/장소 : 20개 (pl001~pl020)
// 나라 : 20개 (cn001~cn020)
// 언어 : 15개 (lg001~lg015)
// 춤의 종류 : 15개 (dn001~dn015)
// 합계 : 471개
// ══════════════════════════════════════════════════════════════
const RAW_QUIZ_DATA = [
// ── 드라마 OST (16개) ──────────────────────────────────────
{ id: 'k001', category: '드라마', youtubeId: 'aE0eV2YR51k', youtubeStart: 55, youtubeEnd: 65, hint: '2016년 대히트 군인 드라마', answers: ['태양의 후예', '태양의후예', 'descendants of the sun'], difficulty: 1 },
{ id: 'k002', category: '드라마', youtubeId: 'pcKR0LPwoYs', youtubeStart: 43, youtubeEnd: 53, hint: '불멸의 존재가 주인공인 판타지 드라마', answers: ['도깨비', 'goblin'], difficulty: 1 },
{ id: 'k003', category: '드라마', youtubeId: 'D07Q2k04uCU', youtubeStart: 60, youtubeEnd: 70, hint: '외계인과 사람의 사랑 이야기', answers: ['별에서 온 그대', '별에서온그대', 'you who came from the stars', 'my love from the star'], difficulty: 2 },
{ id: 'k004', category: '드라마', youtubeId: 'O0StKlRHVeE', youtubeStart: 55, youtubeEnd: 65, hint: '작은 포차에서 시작하는 복수극', answers: ['이태원 클라쓰', '이태원클라쓰', 'itaewon class'], difficulty: 2 },
{ id: 'k005', category: '드라마', youtubeId: 'jGGQyqohOaw', youtubeStart: 60, youtubeEnd: 70, hint: '북한에 불시착한 재벌 여자와 군인의 사랑', answers: ['사랑의 불시착', '사랑의불시착', 'crash landing on you'], difficulty: 1 },
{ id: 'k006', category: '드라마', youtubeId: 'bLoO0FSXncg', youtubeStart: 45, youtubeEnd: 55, hint: '쌍문동 골목 친구들의 청춘 이야기', answers: ['응답하라 1988', '응답하라1988', 'reply 1988'], difficulty: 2 },
{ id: 'k007', category: '드라마', youtubeId: 'FcxEI4v8ASY', youtubeStart: 60, youtubeEnd: 70, hint: '구한말 시대 배경의 역사 드라마', answers: ['미스터 션샤인', '미스터션샤인', 'mr sunshine'], difficulty: 2 },
{ id: 'k008', category: '드라마', youtubeId: 'gIM3cz4_Bpw', youtubeStart: 65, youtubeEnd: 75, hint: '1998년 IMF 시절 두 남녀의 성장 이야기', answers: ['스물다섯 스물하나', '스물다섯스물하나', '25 21'], difficulty: 2 },
{ id: 'k009', category: '드라마', youtubeId: 'x-YJTJsVQ_0', youtubeStart: 50, youtubeEnd: 60, hint: '조선시대 좀비 드라마', answers: ['킹덤', 'kingdom'], difficulty: 3 },
{ id: 'k010', category: '드라마', youtubeId: 'uioEi8ZeV9s', youtubeStart: 20, youtubeEnd: 30, hint: '넷플릭스 세계적 히트 서바이벌 드라마', answers: ['오징어 게임', '오징어게임', 'squid game'], difficulty: 1 },
{ id: 'vm05', category: '드라마', youtubeId: 'DuyFRw33NvM', youtubeStart: 60, youtubeEnd: 70, hint: '류선재가 임솔을 위해 부른 자작곡 (선재 업고 튀어 OST)', answers: ['선재 업고 튀어', '선재업고튀어'], difficulty: 1 },
{ id: 'vm06', category: '드라마', youtubeId: 'fBB4MaBybyg', youtubeStart: 62, youtubeEnd: 72, hint: '선재 업고 튀어의 시원한 밴드 곡', answers: ['선재 업고 튀어', '선재업고튀어'], difficulty: 2 },
{ id: 'vm07', category: '드라마', youtubeId: 'oaDN43yANpQ', youtubeStart: 58, youtubeEnd: 68, hint: '눈물의 여왕 OST (크러쉬)', answers: ['눈물의 여왕', '눈물의여왕'], difficulty: 2 },
{ id: 'vm08', category: '드라마', youtubeId: 'H3ryYBoay3c', youtubeStart: 45, youtubeEnd: 55, hint: '눈물의 여왕 통통 튀는 OST (BSS)', answers: ['눈물의 여왕', '눈물의여왕'], difficulty: 2 },
{ id: 'vm09', category: '드라마', youtubeId: 'Iu2KFp9dJ4I', youtubeStart: 55, youtubeEnd: 65, hint: '그 해 우리는 OST (비비)', answers: ['그 해 우리는', '그해우리는'], difficulty: 3 },
{ id: 'vm10', category: '드라마', youtubeId: 'UoBsiQW23IY', youtubeStart: 48, youtubeEnd: 58, hint: '사내맞선 달콤한 OST (멜로망스)', answers: ['사내맞선', '사내 맞선'], difficulty: 2 },
// ── 가요 (67개) ───────────────────────────────────────────
{ id: 'p001', category: '가요', youtubeId: 'gdZLi9oWNZg', youtubeStart: 46, youtubeEnd: 56, hint: 'BTS의 영어 곡, 전 세계 1위', answers: ['다이너마이트', 'dynamite'], difficulty: 1 },
{ id: 'p002', category: '가요', youtubeId: 'jeqdYqsrsA0', youtubeStart: 268, youtubeEnd: 278, hint: '아이유의 3단 고음으로 유명한 노래', answers: ['좋은 날', '좋은날', 'good day'], difficulty: 1 },
{ id: 'p003', category: '가요', youtubeId: 'IHNzOHi8sJs', youtubeStart: 55, youtubeEnd: 65, hint: '블랙핑크의 대표곡', answers: ['뚜두뚜두', 'ddu-du ddu-du'], difficulty: 1 },
{ id: 'p004', category: '가요', youtubeId: '9bZkp7q19f0', youtubeStart: 50, youtubeEnd: 60, hint: '전 세계를 강타한 말춤 노래', answers: ['강남스타일', 'gangnam style'], difficulty: 1 },
{ id: 'p005', category: '가요', youtubeId: 'I3dezFzsNss', youtubeStart: 47, youtubeEnd: 57, hint: 'EXO의 으르렁거리는 노래', answers: ['으르렁', 'growl'], difficulty: 2 },
{ id: 'p006', category: '가요', youtubeId: '11cta61wi0g', youtubeStart: 50, youtubeEnd: 60, hint: '뉴진스의 데뷔곡', answers: ['하입보이', 'hype boy'], difficulty: 1 },
{ id: 'p007', category: '가요', youtubeId: 'c7rCyll5AeY', youtubeStart: 55, youtubeEnd: 65, hint: '트와이스의 샤샤샤 노래', answers: ['치얼업', 'cheer up'], difficulty: 1 },
{ id: 'p008', category: '가요', youtubeId: 'MBdVXkSdhwU', youtubeStart: 75, youtubeEnd: 85, hint: 'BTS의 DNA', answers: ['dna', '디엔에이'], difficulty: 2 },
{ id: 'p009', category: '가요', youtubeId: '4TWR90KJl84', youtubeStart: 40, youtubeEnd: 50, hint: '에스파의 넥스트 레벨', answers: ['넥스트 레벨', 'next level'], difficulty: 2 },
{ id: 'p010', category: '가요', youtubeId: 'tF27TNC_4pc', youtubeStart: 55, youtubeEnd: 65, hint: '싸이의 흠뻑쇼 대표곡', answers: ['나팔바지'], difficulty: 3 },
{ id: 'p011', category: '가요', youtubeId: 'AAbokV76tkU', youtubeStart: 75, youtubeEnd: 85, hint: '빅뱅의 WOW FANTASTIC BABY', answers: ['판타스틱 베이비', 'fantastic baby'], difficulty: 1 },
{ id: 'p012', category: '가요', youtubeId: 'XsX3ATc3FbA', youtubeStart: 55, youtubeEnd: 65, hint: 'BTS X 할시 컬래버레이션', answers: ['작은 것들을 위한 시', 'boy with luv'], difficulty: 2 },
{ id: 'p013', category: '가요', youtubeId: 'TgOu00Mf3kI', youtubeStart: 60, youtubeEnd: 70, hint: '아이유 X 슈가 콜라보', answers: ['에잇', 'eight'], difficulty: 2 },
{ id: 'p014', category: '가요', youtubeId: 'Dab4EENTW5I', youtubeStart: 60, youtubeEnd: 70, hint: '스트레이 키즈의 마이로', answers: ['미로', 'miroh'], difficulty: 3 },
{ id: 'p015', category: '가요', youtubeId: 'J-wFp43XOrA', youtubeStart: 60, youtubeEnd: 70, hint: '세븐틴의 아주 Nice', answers: ['아주 나이스', 'very nice'], difficulty: 3 },
{ id: 'kg01', category: '가요', youtubeId: 'pSUydWEqKwE', youtubeStart: 43, youtubeEnd: 53, hint: '뉴진스의 우~ 우우우~', answers: ['ditto', '디토'], difficulty: 1 },
{ id: 'kg02', category: '가요', youtubeId: 'ArmDp-zijuc', youtubeStart: 33, youtubeEnd: 43, hint: 'Im super shy, super shy', answers: ['super shy', '슈퍼 샤이'], difficulty: 1 },
{ id: 'kg03', category: '가요', youtubeId: 'Q3K0TOvTOno', youtubeStart: 52, youtubeEnd: 62, hint: '뉴진스의 달콤한 신곡 (2024)', answers: ['how sweet', '하우스윗'], difficulty: 2 },
{ id: 'kg04', category: '가요', youtubeId: 'Y8JFxS1HlDo', youtubeStart: 57, youtubeEnd: 67, hint: '숨참고 LOVE DIVE', answers: ['love dive', '러브 다이브'], difficulty: 1 },
{ id: 'kg05', category: '가요', youtubeId: '6ZUIwj3FgUY', youtubeStart: 44, youtubeEnd: 54, hint: 'Thats my life is a 아름다운 갤럭시', answers: ['i am', '아이엠'], difficulty: 1 },
{ id: 'kg06', category: '가요', youtubeId: '07EzMbVH3QE', youtubeStart: 48, youtubeEnd: 58, hint: '해야 해야 해야 한입에 널 삼킬게', answers: ['해야', 'heya'], difficulty: 2 },
{ id: 'kg07', category: '가요', youtubeId: 'phuiiNCxRMg', youtubeStart: 39, youtubeEnd: 49, hint: '사건은 다가와 Ah Oh Ay', answers: ['supernova', '슈퍼노바'], difficulty: 1 },
{ id: 'kg08', category: '가요', youtubeId: '4TWR90KJl84', youtubeStart: 55, youtubeEnd: 65, hint: 'Im on the Next Level', answers: ['next level', '넥스트 레벨'], difficulty: 1 },
{ id: 'kg09', category: '가요', youtubeId: 'D8VEhcPeSlc', youtubeStart: 46, youtubeEnd: 56, hint: '에스파의 트라우마를 깨는 곡', answers: ['drama', '드라마'], difficulty: 2 },
{ id: 'kg10', category: '가요', youtubeId: 'pyf8cbqyfPs', youtubeStart: 41, youtubeEnd: 51, hint: 'Anti ti ti ti fragile', answers: ['antifragile', '안티프래자일'], difficulty: 1 },
{ id: 'kg11', category: '가요', youtubeId: 'hLvWy2b857I', youtubeStart: 36, youtubeEnd: 46, hint: '르세라핌의 오버워치 콜라보 곡', answers: ['perfect night', '퍼펙트 나이트'], difficulty: 2 },
{ id: 'kg12', category: '가요', youtubeId: 'KNexS61fjus', youtubeStart: 49, youtubeEnd: 59, hint: '골반을 튕기는 스마트한 춤', answers: ['smart', '스마트'], difficulty: 2 },
{ id: 'kg13', category: '가요', youtubeId: '7HDeem-JaSY', youtubeStart: 58, youtubeEnd: 68, hint: '아임 어 퀸카! 아임 어 퀸카!', answers: ['퀸카', 'queencard'], difficulty: 1 },
{ id: 'kg14', category: '가요', youtubeId: 'ATK7gAaZTOM', youtubeStart: 71, youtubeEnd: 81, hint: '미친 연주, 나는 아픈 건 딱 질색이니까', answers: ['나는 아픈 건 딱 질색이니까', 'fate'], difficulty: 1 },
{ id: 'kg15', category: '가요', youtubeId: 'Vk5-c_v4gMU', youtubeStart: 42, youtubeEnd: 52, hint: '슈퍼 이끌림~ (아일릿)', answers: ['마그네틱', 'magnetic'], difficulty: 1 },
{ id: 'kg16', category: '가요', youtubeId: '2wA_b6YHjqQ', youtubeStart: 52, youtubeEnd: 62, hint: 'YG 신인 베이비몬스터의 괴물 같은 데뷔곡', answers: ['sheesh', '쉬시'], difficulty: 2 },
{ id: 'kg17', category: '가요', youtubeId: 'IajeQM00yfE', youtubeStart: 37, youtubeEnd: 47, hint: '키스오브라이프의 끈적한 여름 노래', answers: ['sticky', '스티키'], difficulty: 2 },
{ id: 'kg18', category: '가요', youtubeId: '7UecFm_bSTU', youtubeStart: 63, youtubeEnd: 73, hint: '엔믹스의 믹스팝 정수', answers: ['dash', '대시'], difficulty: 3 },
{ id: 'kg19', category: '가요', youtubeId: 'SxHmoifp0oQ', youtubeStart: 51, youtubeEnd: 61, hint: '스테이씨의 곰돌이 춤', answers: ['teddy bear', '테디 베어'], difficulty: 2 },
{ id: 'kg20', category: '가요', youtubeId: '9JFi7MmjtGA', youtubeStart: 47, youtubeEnd: 57, hint: '비비지의 숨겨진 명곡', answers: ['maniac', '매니악'], difficulty: 3 },
{ id: 'kb01', category: '가요', youtubeId: 'QU9c0053UAU', youtubeStart: 54, youtubeEnd: 64, hint: '정국의 빌보드 1위 데뷔곡', answers: ['seven', '세븐'], difficulty: 1 },
{ id: 'kb02', category: '가요', youtubeId: 'nOI67IDlNMQ', youtubeStart: 46, youtubeEnd: 56, hint: '지민의 몽환적인 솔로 1위 곡', answers: ['like crazy', '라이크 크레이지'], difficulty: 2 },
{ id: 'kb03', category: '가요', youtubeId: '-GQg25oP0S4', youtubeStart: 61, youtubeEnd: 71, hint: '마치 된 것 같아 손오공', answers: ['손오공', 'super'], difficulty: 1 },
{ id: 'kb04', category: '가요', youtubeId: 'zSQ48zyWZrY', youtubeStart: 49, youtubeEnd: 59, hint: '세븐틴의 쿵치팍치 쿵쿵치팍치', answers: ['음악의 신'], difficulty: 2 },
{ id: 'kb05', category: '가요', youtubeId: 'mBXBOLG06Wc', youtubeStart: 38, youtubeEnd: 48, hint: '부석순의 직장인 응원가', answers: ['파이팅 해야지', '파이팅해야지'], difficulty: 1 },
{ id: 'kb06', category: '가요', youtubeId: 'JsOOis4bBFg', youtubeStart: 43, youtubeEnd: 53, hint: '별의별의별의별의 특!', answers: ['특', 's-class', 's class'], difficulty: 2 },
{ id: 'kb07', category: '가요', youtubeId: 'P9tKTxbgdkk', youtubeStart: 52, youtubeEnd: 62, hint: 'TXT의 몽환적인 유혹', answers: ['sugar rush ride', '슈가 러시 라이드'], difficulty: 3 },
{ id: 'kb08', category: '가요', youtubeId: 'iUw3LPM7OBU', youtubeStart: 41, youtubeEnd: 51, hint: '라이즈의 펑키한 기타 리프', answers: ['get a guitar', '겟 어 기타'], difficulty: 2 },
{ id: 'kb09', category: '가요', youtubeId: '0TAAUWHo4Ec', youtubeStart: 57, youtubeEnd: 67, hint: '라이즈의 첫사랑 기억 조작 곡', answers: ['love 119', '러브 119'], difficulty: 2 },
{ id: 'kb10', category: '가요', youtubeId: 'hVAc1Vf2ITU', youtubeStart: 44, youtubeEnd: 54, hint: '첫 만남은 너무 어려워~ (TWS)', answers: ['첫 만남은 계획대로 되지 않아'], difficulty: 1 },
{ id: 'kb11', category: '가요', youtubeId: 'FxB6_qaqHlY', youtubeStart: 48, youtubeEnd: 58, hint: '플레이브의 버추얼 히트곡', answers: ['way 4 luv', '웨이 포 러브'], difficulty: 3 },
{ id: 'kb12', category: '가요', youtubeId: 'BS7tz2rAOSA', youtubeStart: 63, youtubeEnd: 73, hint: '데이식스의 전설적인 벚꽃 연금곡', answers: ['예뻤어'], difficulty: 1 },
{ id: 'kb13', category: '가요', youtubeId: 'vnS_jn2uibs', youtubeStart: 66, youtubeEnd: 76, hint: '데이식스의 청춘 만화 같은 곡', answers: ['한 페이지가 될 수 있게'], difficulty: 1 },
{ id: 'kb14', category: '가요', youtubeId: 'RowlrvmyFEk', youtubeStart: 51, youtubeEnd: 61, hint: '이것이 우리만의 쇼~ (데이식스 최신곡)', answers: ['welcome to the show', '웰컴 투 더 쇼'], difficulty: 2 },
{ id: 'kb15', category: '가요', youtubeId: 'ImuWa3SJulY', youtubeStart: 58, youtubeEnd: 68, hint: '유튜버 김계란이 만든 걸밴드의 역주행 신화', answers: ['고민중독'], difficulty: 1 },
{ id: 'ks01', category: '가요', youtubeId: 'xfqBQ2XhBCg', youtubeStart: 49, youtubeEnd: 59, hint: '지코와 제니의 콜라보', answers: ['spot', '스팟'], difficulty: 1 },
{ id: 'ks02', category: '가요', youtubeId: 'C_cpDd0WYTk', youtubeStart: 41, youtubeEnd: 51, hint: '스우파 리더즈가 췄던 지코의 노래', answers: ['새삥'], difficulty: 2 },
{ id: 'ks03', category: '가요', youtubeId: 'EIz09kLzN9k', youtubeStart: 52, youtubeEnd: 62, hint: '악뮤의 큐피드 화살', answers: ['love lee', '러브리', '러블리'], difficulty: 1 },
{ id: 'ks04', category: '가요', youtubeId: 'wAjOqRl1XpE', youtubeStart: 61, youtubeEnd: 71, hint: '거위도 아니고 타조도 아니고', answers: ['후라이의 꿈'], difficulty: 2 },
{ id: 'ks05', category: '가요', youtubeId: 'JleoAppaxi0', youtubeStart: 57, youtubeEnd: 67, hint: '아이유와 뷔가 출연한 디스토피아 뮤비', answers: ['love wins all', '러브 윈즈 올'], difficulty: 1 },
{ id: 'ks06', category: '가요', youtubeId: 'mFbILexYSQg', youtubeStart: 46, youtubeEnd: 56, hint: '아이유의 신나는 홀씨', answers: ['홀씨'], difficulty: 2 },
{ id: 'ks07', category: '가요', youtubeId: '5_n6t9G2TUQ', youtubeStart: 54, youtubeEnd: 64, hint: '태연의 감성적인 이별 노래', answers: ['to x', '투 엑스'], difficulty: 2 },
{ id: 'ks08', category: '가요', youtubeId: 'Crq_fRV0O0E', youtubeStart: 43, youtubeEnd: 53, hint: '아이 러브 마이 바디~ (화사)', answers: ['i love my body', '아이 러브 마이 바디'], difficulty: 2 },
{ id: 'ks09', category: '가요', youtubeId: '11iZcYbq_is', youtubeStart: 49, youtubeEnd: 59, hint: '이영지와 도경수의 간질간질한 듀엣', answers: ['small girl', '스몰 걸'], difficulty: 1 },
{ id: 'ks10', category: '가요', youtubeId: 'LKQ-18LoFQk', youtubeStart: 68, youtubeEnd: 78, hint: '임영웅의 감성 발라드 최고봉', answers: ['사랑은 늘 도망가'], difficulty: 1 },
{ id: 'ks11', category: '가요', youtubeId: 'yFlxYHjHYAw', youtubeStart: 60, youtubeEnd: 70, hint: '박재정의 폭발적인 고음 발라드', answers: ['헤어지자 말해요'], difficulty: 1 },
{ id: 'ks12', category: '가요', youtubeId: 'BBdC1rl5sKY', youtubeStart: 64, youtubeEnd: 74, hint: '윤하의 역주행 천문학 노래', answers: ['사건의 지평선'], difficulty: 1 },
{ id: 'ks13', category: '가요', youtubeId: 'smdmEhkIRVc', youtubeStart: 35, youtubeEnd: 45, hint: '달디달고 달디달고 달디단~', answers: ['밤양갱'], difficulty: 1 },
{ id: 'ks14', category: '가요', youtubeId: 'PVIf531Dt8E', youtubeStart: 58, youtubeEnd: 68, hint: '이무진의 서정적인 고백송', answers: ['에피소드', 'episode'], difficulty: 2 },
{ id: 'ks15', category: '가요', youtubeId: '7ihLv8_Vd-4', youtubeStart: 60, youtubeEnd: 70, hint: '최유리의 감성 인디 역주행 곡', answers: ['숲'], difficulty: 3 },
{ id: 'vm01', category: '가요', youtubeId: 'ekr2nIex040', youtubeStart: 42, youtubeEnd: 52, hint: '2024년 최고의 메가 히트 콜라보 (로제 & 브루노 마스)', answers: ['apt', '아파트'], difficulty: 1 },
{ id: 'vm04', category: '가요', youtubeId: 'LuvJLjB8nBw', youtubeStart: 60, youtubeEnd: 70, hint: 'T의 성향을 묻는 인디 밈 곡', answers: ['티라미수 케익', '티라미수케익'], difficulty: 1 },
// ── 팝송 (45개) ───────────────────────────────────────────
{ id: 'w001', category: '팝송', youtubeId: 'JGwWNGJdvx8', youtubeStart: 46, youtubeEnd: 56, hint: 'Ed Sheeran의 전 세계 1위 곡', answers: ['shape of you'], difficulty: 1 },
{ id: 'w002', category: '팝송', youtubeId: '4NRXx6U8ABQ', youtubeStart: 58, youtubeEnd: 68, hint: '80년대 신스팝 느낌의 더 위켄드 곡', answers: ['blinding lights', '블라인딩 라이츠'], difficulty: 1 },
{ id: 'w003', category: '팝송', youtubeId: '34Na4j8AVgA', youtubeStart: 35, youtubeEnd: 45, hint: '다프트 펑크와 함께한 더 위켄드 곡', answers: ['starboy', '스타보이'], difficulty: 2 },
{ id: 'w004', category: '팝송', youtubeId: 'nYh-n7EOtMA', youtubeStart: 50, youtubeEnd: 60, hint: 'Sia의 돈 없어도 즐거운 노래', answers: ['cheap thrills', '칩 스릴스'], difficulty: 1 },
{ id: 'w005', category: '팝송', youtubeId: 'H5v3kku4y6Q', youtubeStart: 45, youtubeEnd: 55, hint: '해리 스타일스의 솔로 대표곡', answers: ['as it was'], difficulty: 1 },
{ id: 'w006', category: '팝송', youtubeId: 'ZmDBbnmKpqQ', youtubeStart: 60, youtubeEnd: 70, hint: '올리비아 로드리고의 데뷔 싱글', answers: ['drivers license', '드라이버스 라이센스'], difficulty: 2 },
{ id: 'w007', category: '팝송', youtubeId: 'rYEDA3JcQqw', youtubeStart: 65, youtubeEnd: 75, hint: '아델의 복수심 가득한 노래', answers: ['rolling in the deep', '롤링 인 더 딥'], difficulty: 1 },
{ id: 'w008', category: '팝송', youtubeId: 'gl1aHhXnN1k', youtubeStart: 55, youtubeEnd: 65, hint: '전 남자친구들에게 감사하는 노래', answers: ['thank u next', 'thank you next'], difficulty: 1 },
{ id: 'w009', category: '팝송', youtubeId: 'b1kbLwvqugk', youtubeStart: 50, youtubeEnd: 60, hint: '테일러 스위프트의 It's me, hi', answers: ['anti hero', 'anti-hero'], difficulty: 1 },
{ id: 'w010', category: '팝송', youtubeId: 'DyDfgMOUjCI', youtubeStart: 72, youtubeEnd: 82, hint: '빌리 아일리시의 duh~', answers: ['bad guy', '배드 가이'], difficulty: 1 },
{ id: 'w011', category: '팝송', youtubeId: 'VbfpW0pbvaU', youtubeStart: 50, youtubeEnd: 60, hint: '숀 멘데스의 상처 노래', answers: ['stitches', '스티치스'], difficulty: 2 },
{ id: 'w012', category: '팝송', youtubeId: 'fRh_vgS2dFE', youtubeStart: 55, youtubeEnd: 65, hint: '저스틴 비버의 미안하다는 노래', answers: ['sorry'], difficulty: 1 },
{ id: 'w013', category: '팝송', youtubeId: 'PT2_F-1esPk', youtubeStart: 65, youtubeEnd: 75, hint: '체인스모커스 X 홀지', answers: ['closer', '클로저'], difficulty: 2 },
{ id: 'w014', category: '팝송', youtubeId: 'TUVcZfQe-Kw', youtubeStart: 50, youtubeEnd: 60, hint: '두아 리파의 우주적인 노래', answers: ['levitating', '레비테이팅'], difficulty: 1 },
{ id: 'w015', category: '팝송', youtubeId: 'OPf0YbXqDm0', youtubeStart: 58, youtubeEnd: 68, hint: '브루노 마스의 업타운 펑크', answers: ['uptown funk', '업타운 펑크'], difficulty: 1 },
{ id: 'wp01', category: '팝송', youtubeId: 'Oa_RSwwpPaA', youtubeStart: 53, youtubeEnd: 63, hint: 'Please stay~ 벤슨 분의 틱톡 떡상 곡', answers: ['beautiful things', '뷰티풀 띵스'], difficulty: 1 },
{ id: 'wp02', category: '팝송', youtubeId: 'GZ3zL7kT6_c', youtubeStart: 47, youtubeEnd: 57, hint: '테디 스윔스의 거친 소울 히트곡', answers: ['lose control', '루즈 컨트롤'], difficulty: 2 },
{ id: 'wp03', category: '팝송', youtubeId: 'eVli-tstM5E', youtubeStart: 36, youtubeEnd: 46, hint: '사브리나 카펜터의 카페인 같은 노래', answers: ['espresso', '에스프레소'], difficulty: 1 },
{ id: 'wp04', category: '팝송', youtubeId: 'cF1Na4AIecM', youtubeStart: 49, youtubeEnd: 59, hint: '제발 날 울리지 마 (Sabrina Carpenter)', answers: ['please please please', '플리즈 플리즈 플리즈'], difficulty: 2 },
{ id: 'wp05', category: '팝송', youtubeId: 'ic8j13piAhQ', youtubeStart: 62, youtubeEnd: 72, hint: '테일러 스위프트의 잔인한 여름', answers: ['cruel summer', '크루엘 섬머'], difficulty: 1 },
{ id: 'wp06', category: '팝송', youtubeId: 'b1kbLwvqugk', youtubeStart: 44, youtubeEnd: 54, hint: 'Its me, hi, Im the problem (Taylor Swift)', answers: ['anti hero', 'anti-hero', '안티 히어로'], difficulty: 1 },
{ id: 'wp07', category: '팝송', youtubeId: 'Mx92lTYxrJQ', youtubeStart: 50, youtubeEnd: 60, hint: '더 위켄드와 제니의 아찔한 콜라보', answers: ['one of the girls', '원 오브 더 걸스'], difficulty: 2 },
{ id: 'wp08', category: '팝송', youtubeId: 'KNtJGQkC-WI', youtubeStart: 41, youtubeEnd: 51, hint: '아리아나 그란데의 "우리는 친구가 될 수 없어"', answers: ["we can't be friends", 'we cant be friends'], difficulty: 1 },
{ id: 'wp09', category: '팝송', youtubeId: 'cW8VLC9nnTo', youtubeStart: 74, youtubeEnd: 84, hint: '빌리 아일리시의 바비 OST', answers: ['what was i made for'], difficulty: 2 },
{ id: 'wp10', category: '팝송', youtubeId: 'V9PVRfjEBTI', youtubeStart: 51, youtubeEnd: 61, hint: '빌리 아일리시의 새가 된 듯한 곡', answers: ['birds of a feather', '버즈 오브 어 페더'], difficulty: 2 },
{ id: 'wp11', category: '팝송', youtubeId: 'suAR1PYFNYA', youtubeStart: 45, youtubeEnd: 55, hint: '두아 리파의 Catch me or I go', answers: ['houdini', '후디니'], difficulty: 2 },
{ id: 'wp12', category: '팝송', youtubeId: 'OiC1rgCPmUQ', youtubeStart: 39, youtubeEnd: 49, hint: '두아 리파의 신나는 댄스 넘버', answers: ['dance the night', '댄스 더 나이트'], difficulty: 2 },
{ id: 'wp13', category: '팝송', youtubeId: 'm4_9TFeMfJE', youtubeStart: 56, youtubeEnd: 66, hint: '도자 캣의 붉게 물들여', answers: ['paint the town red'], difficulty: 2 },
{ id: 'wp14', category: '팝송', youtubeId: 'XoiOOiuH8iI', youtubeStart: 37, youtubeEnd: 47, hint: '타일라의 관능적인 아프로비츠 곡', answers: ['water', '워터'], difficulty: 1 },
{ id: 'wp15', category: '팝송', youtubeId: 'RlPNh_PBZb4', youtubeStart: 59, youtubeEnd: 69, hint: '올리비아 로드리고의 뱀파이어', answers: ['vampire', '뱀파이어'], difficulty: 1 },
{ id: 'wp16', category: '팝송', youtubeId: 'gNi_6U5Pm_o', youtubeStart: 43, youtubeEnd: 53, hint: '올리비아 로드리고의 펑크 록 하이틴', answers: ['good 4 u', 'good for you'], difficulty: 2 },
{ id: 'wp17', category: '팝송', youtubeId: 'H5v3kku4y6Q', youtubeStart: 49, youtubeEnd: 59, hint: '해리 스타일스의 감각적인 솔로곡', answers: ['as it was'], difficulty: 1 },
{ id: 'wp18', category: '팝송', youtubeId: 'b53QJYP-lqY', youtubeStart: 52, youtubeEnd: 62, hint: '트로이 시반의 신나는 클럽 트랙', answers: ['rush', '러시'], difficulty: 2 },
{ id: 'wp19', category: '팝송', youtubeId: 'a7GITgqwDVg', youtubeStart: 44, youtubeEnd: 54, hint: '찰리 푸스와 정국의 좌우 음향 곡', answers: ['left and right', '레프트 앤 라이트'], difficulty: 1 },
{ id: 'wp20', category: '팝송', youtubeId: 'TBXQu8ORnBQ', youtubeStart: 63, youtubeEnd: 73, hint: '한국에서 역주행한 찰리 푸스 명곡', answers: ['dangerously', '데인저러스리'], difficulty: 2 },
{ id: 'wp21', category: '팝송', youtubeId: 'G7KNmW9a75Y', youtubeStart: 46, youtubeEnd: 56, hint: '마일리 사이러스의 당당한 1위 곡', answers: ['flowers', '플라워스'], difficulty: 1 },
{ id: 'wp22', category: '팝송', youtubeId: 'MSRcC626prw', youtubeStart: 57, youtubeEnd: 67, hint: 'SZA의 전 남친 저격 노래', answers: ['kill bill', '킬 빌'], difficulty: 2 },
{ id: 'wp23', category: '팝송', youtubeId: 'oftolPu9qp4', youtubeStart: 35, youtubeEnd: 45, hint: '핑크팬서레스의 틱톡 화제곡', answers: ["boy's a liar", 'boys a liar'], difficulty: 3 },
{ id: 'wp24', category: '팝송', youtubeId: 'kTJczUoc26U', youtubeStart: 41, youtubeEnd: 51, hint: '더 키드 라로이 & 저스틴 비버', answers: ['stay', '스테이'], difficulty: 1 },
{ id: 'wp25', category: '팝송', youtubeId: 'Uq9gPaIzbe8', youtubeStart: 52, youtubeEnd: 62, hint: '샘 스미스의 불경한(?) 댄스곡', answers: ['unholy', '언홀리'], difficulty: 1 },
{ id: 'wp26', category: '팝송', youtubeId: 'GxldQ9eX2wo', youtubeStart: 63, youtubeEnd: 73, hint: '스티븐 산체스의 복고풍 로맨스', answers: ['until i found you', '언틸 아이 파운드 유'], difficulty: 3 },
{ id: 'wp27', category: '팝송', youtubeId: 'adLGHcj_fmA', youtubeStart: 58, youtubeEnd: 68, hint: '브루노 마스의 실크 소닉 문 열어둬', answers: ['leave the door open', '리브 더 도어 오픈'], difficulty: 2 },
{ id: 'wp28', category: '팝송', youtubeId: 'Il0S8BoucSA', youtubeStart: 49, youtubeEnd: 59, hint: '에드 시런의 몸이 떨리는 노래', answers: ['shivers', '시버스'], difficulty: 2 },
{ id: 'wp29', category: '팝송', youtubeId: 'PEM0Vs8jf1w', youtubeStart: 61, youtubeEnd: 71, hint: 'JVKE의 아름다운 황금빛 피아노', answers: ['golden hour', '골든 아워'], difficulty: 2 },
{ id: 'wp30', category: '팝송', youtubeId: 'uPD0QOGTmMI', youtubeStart: 48, youtubeEnd: 58, hint: '더 위켄드의 틱톡 역주행 명곡', answers: ['die for you', '다이 포 유'], difficulty: 2 },
// ── 영화 OST (10개) ───────────────────────────────────────
{ id: 'm001', category: '영화', youtubeId: 'GT-SfFbFGsY', youtubeStart: 20, youtubeEnd: 30, hint: '2019 칸 영화제 황금종려상 수상 영화', answers: ['기생충', 'parasite'], difficulty: 2 },
{ id: 'm002', category: '영화', youtubeId: '2uMX_opOvDI', youtubeStart: 60, youtubeEnd: 70, hint: '첫사랑을 다룬 로맨스 영화', answers: ['건축학개론', 'architecture 101'], difficulty: 3 },
{ id: 'm003', category: '영화', youtubeId: 'FOLccTgFJz8', youtubeStart: 18, youtubeEnd: 28, hint: '80년대 여고생들의 우정 이야기', answers: ['써니', 'sunny'], difficulty: 2 },
{ id: 'm004', category: '영화', youtubeId: '5O5PVvHTWRo', youtubeStart: 0, youtubeEnd: 10, hint: '저승 삼차사와 함께하는 심판 이야기', answers: ['신과 함께', '신과함께', 'along with the gods'], difficulty: 2 },
{ id: 'm005', category: '영화', youtubeId: 'xM1CIQd_X4c', youtubeStart: 0, youtubeEnd: 10, hint: '치킨집을 운영하는 마약반 형사들', answers: ['극한직업', 'extreme job'], difficulty: 3 },
{ id: 'a003', category: '영화', youtubeId: 'm3zvVGJrTP8', youtubeStart: 120, youtubeEnd: 130, hint: '크리스토퍼 놀란 감독의 우주 영화', answers: ['인터스텔라', 'interstellar'], difficulty: 2 },
{ id: 'a006', category: '영화', youtubeId: 'fJ9rUzIMcZQ', youtubeStart: 45, youtubeEnd: 55, hint: '퀸의 전기 영화', answers: ['보헤미안 랩소디', 'bohemian rhapsody'], difficulty: 1 },
{ id: 'a007', category: '영화', youtubeId: 'FOabQZHT4qY', youtubeStart: 60, youtubeEnd: 70, hint: '마블 히어로들의 집합', answers: ['어벤져스', 'avengers'], difficulty: 1 },
{ id: 'a008', category: '영화', youtubeId: 'cZAw8qxn0ZE', youtubeStart: 50, youtubeEnd: 60, hint: '재즈 피아니스트와 배우 지망생의 사랑', answers: ['라라랜드', 'la la land', 'city of stars'], difficulty: 2 },
{ id: 'a009', category: '영화', youtubeId: 'Imu4CmE6Nmg', youtubeStart: 5, youtubeEnd: 15, hint: '거미줄을 타는 히어로', answers: ['스파이더맨', 'spider-man', 'spiderman'], difficulty: 1 },
{ id: 'a010', category: '영화', youtubeId: 'yK0P1Bk8Cx4', youtubeStart: 50, youtubeEnd: 60, hint: '전투기 파일럿의 이야기, 2022년 속편', answers: ['탑건', 'top gun', '탑건 매버릭', 'top gun maverick'], difficulty: 2 },
// ── 애니메이션 OST (29개) ──────────────────────────────────
{ id: 'a001', category: '애니메이션', youtubeId: 'L0MK7qz13bU', youtubeStart: 60, youtubeEnd: 70, hint: '눈의 여왕이 부르는 노래', answers: ['렛잇고', 'let it go', '겨울왕국', 'frozen'], difficulty: 1 },
{ id: 'a002', category: '애니메이션', youtubeId: 'GibiNy4d4gc', youtubeStart: 25, youtubeEnd: 35, hint: '아프리카 초원의 왕 이야기', answers: ['라이온킹', 'lion king', 'circle of life'], difficulty: 1 },
{ id: 'a004', category: '애니메이션', youtubeId: '1MPZRcyTrcU', youtubeStart: 7, youtubeEnd: 17, hint: '장난감들의 우정 이야기', answers: ['토이스토리', 'toy story', "you've got a friend in me"], difficulty: 1 },
{ id: 'a005', category: '애니메이션', youtubeId: 'WUiI5aQcTow', youtubeStart: 0, youtubeEnd: 10, hint: '마법사 학교 호그와트 이야기', answers: ['해리포터', 'harry potter', 'hedwigs theme'], difficulty: 1 },
{ id: 'an001', category: '애니메이션', youtubeId: '0OdExTY2D8M', youtubeStart: 33, youtubeEnd: 43, hint: '해적왕이 되겠다 루피의 모험', answers: ['원피스', 'one piece'], difficulty: 1 },
{ id: 'an002', category: '애니메이션', youtubeId: 'E_BsL8_cFnE', youtubeStart: 33, youtubeEnd: 43, hint: '피카츄 포켓몬 마스터', answers: ['포켓몬스터', '포켓몬', 'pokemon'], difficulty: 1 },
{ id: 'an003', category: '애니메이션', youtubeId: 'kmrONTZnKo0', youtubeStart: 52, youtubeEnd: 62, hint: '목숨을 건 결투 유희왕', answers: ['유희왕', 'yu-gi-oh'], difficulty: 1 },
{ id: 'an004', category: '애니메이션', youtubeId: 'AE4b9jO1uB4', youtubeStart: 54, youtubeEnd: 64, hint: '닌자 나루토와 동료들의 이야기', answers: ['나루토', 'naruto'], difficulty: 1 },
{ id: 'an005', category: '애니메이션', youtubeId: '3RVsOcufd9k', youtubeStart: 42, youtubeEnd: 52, hint: '강철의 연금술사 에드워드', answers: ['강철의 연금술사', '풀메탈 알케미스트', 'fullmetal alchemist'], difficulty: 1 },
{ id: 'an006', category: '애니메이션', youtubeId: 'o6wtDPVkKqI', youtubeStart: 48, youtubeEnd: 58, hint: '총을 쏘며 활약하는 에바', answers: ['신세기 에반게리온', '에바', 'evangelion'], difficulty: 2 },
{ id: 'an007', category: '애니메이션', youtubeId: 'Uku3t8qAloc', youtubeStart: 60, youtubeEnd: 70, hint: '귀신을 베는 탄지로의 이야기', answers: ['귀멸의 칼날', '기멸의 칼날', 'demon slayer', 'kimetsu no yaiba'], difficulty: 1 },
{ id: 'an008', category: '애니메이션', youtubeId: 'CID-sYQNCew', youtubeStart: 60, youtubeEnd: 70, hint: '거인을 향해 싸우는 에렌', answers: ['진격의 거인', 'attack on titan'], difficulty: 1 },
{ id: 'an009', category: '애니메이션', youtubeId: 'CbH2F0kXgTY', youtubeStart: 60, youtubeEnd: 70, hint: '스파이 가족 로이드와 아냐', answers: ['스파이 패밀리', 'spy x family'], difficulty: 1 },
{ id: 'an010', category: '애니메이션', youtubeId: '1tk1pqwrOys', youtubeStart: 54, youtubeEnd: 64, hint: '주술을 부리는 이타도리 유지', answers: ['주술회전', 'jujutsu kaisen'], difficulty: 1 },
{ id: 'an011', category: '애니메이션', youtubeId: 'Th7MAZYFIMc', youtubeStart: 52, youtubeEnd: 62, hint: '히로아카 데쿠의 영웅 이야기', answers: ['나의 히어로 아카데미아', '히로아카', 'my hero academia'], difficulty: 1 },
{ id: 'an012', category: '애니메이션', youtubeId: 'c33MnfP0Gfs', youtubeStart: 41, youtubeEnd: 51, hint: '이웃집 토토로 메이와 사츠키', answers: ['이웃집 토토로', '토토로', 'my neighbor totoro'], difficulty: 1 },
{ id: 'an013', category: '애니메이션', youtubeId: 'gtOks_p85_w', youtubeStart: 55, youtubeEnd: 65, hint: '센과 치히로의 행방불명', answers: ['센과 치히로', 'spirited away'], difficulty: 1 },
{ id: 'an014', category: '애니메이션', youtubeId: 'XjBSzdoVVZE', youtubeStart: 30, youtubeEnd: 40, hint: '원령공주 아시타카와 모노노케', answers: ['원령공주', 'princess mononoke'], difficulty: 2 },
{ id: 'an015', category: '애니메이션', youtubeId: 'Hnt32LNVALk', youtubeStart: 8, youtubeEnd: 18, hint: '하울의 움직이는 성', answers: ['하울의 움직이는 성', "howl's moving castle"], difficulty: 1 },
{ id: 'an016', category: '애니메이션', youtubeId: 's4pgnGqkNEU', youtubeStart: 30, youtubeEnd: 40, hint: '미래의 도라에몽 로봇 고양이', answers: ['도라에몽', 'doraemon'], difficulty: 1 },
{ id: 'an017', category: '애니메이션', youtubeId: 'DBEYpGEsOHs', youtubeStart: 18, youtubeEnd: 28, hint: '짱구는 못말려 노하라 신노스케', answers: ['짱구는 못말려', '크레용 신짱', 'crayon shinchan'], difficulty: 1 },
{ id: 'an018', category: '애니메이션', youtubeId: 'mgWONfthS9U', youtubeStart: 60, youtubeEnd: 70, hint: '슬램덩크 강백호의 농구', answers: ['슬램덩크', 'slam dunk'], difficulty: 1 },
{ id: 'an019', category: '애니메이션', youtubeId: 'fGbWJ0YPEH8', youtubeStart: 50, youtubeEnd: 60, hint: '드래곤볼 손오공의 싸움', answers: ['드래곤볼', 'dragon ball'], difficulty: 1 },
{ id: 'an020', category: '애니메이션', youtubeId: 'wW9TwZdWpjw', youtubeStart: 30, youtubeEnd: 40, hint: '블리치 이치고의 사신', answers: ['블리치', 'bleach'], difficulty: 2 },
{ id: 'an021', category: '애니메이션', youtubeId: 'AOqLEZoGpNw', youtubeStart: 40, youtubeEnd: 50, hint: '명탐정 코난 에도가와 코난', answers: ['명탐정 코난', '코난', 'detective conan'], difficulty: 1 },
{ id: 'an022', category: '애니메이션', youtubeId: '6KYk5a93OC8', youtubeStart: 60, youtubeEnd: 70, hint: '세일러문 마법소녀', answers: ['미소녀전사 세일러문', '세일러문', 'sailor moon'], difficulty: 1 },
{ id: 'an023', category: '애니메이션', youtubeId: '6gpcPYDkPdg', youtubeStart: 42, youtubeEnd: 52, hint: '카드캡터 사쿠라 마법 카드', answers: ['카드캡터 사쿠라', 'cardcaptor sakura'], difficulty: 2 },
{ id: 'an024', category: '애니메이션', youtubeId: 'ktcKUrIW2iw', youtubeStart: 30, youtubeEnd: 40, hint: '요괴워치 지바냥', answers: ['요괴워치', 'yokai watch'], difficulty: 1 },
{ id: 'an025', category: '애니메이션', youtubeId: 'oZU6QvWHBxY', youtubeStart: 38, youtubeEnd: 48, hint: '원펀맨 사이타마 한 방으로 끝', answers: ['원펀맨', 'one punch man'], difficulty: 1 },
// ── 동요 (30개) ───────────────────────────────────────────
{ id: 'dy001', category: '동요', youtubeId: 'L6_y2KvGNts', youtubeStart: 5, youtubeEnd: 15, hint: '곰 세 마리가 한 집에 있어', answers: ['곰 세 마리', '곰세마리'], difficulty: 1 },
{ id: 'dy002', category: '동요', youtubeId: 'VSNPr2ydsE0', youtubeStart: 3, youtubeEnd: 13, hint: '나비야 나비야 이리 날아오너라', answers: ['나비야', '나비야나비야'], difficulty: 1 },
{ id: 'dy003', category: '동요', youtubeId: 'B58SWj77cxM', youtubeStart: 5, youtubeEnd: 15, hint: '산토끼 토끼야 어디를 가느냐', answers: ['산토끼', '산토끼토끼야'], difficulty: 1 },
{ id: 'dy004', category: '동요', youtubeId: '5sI14-FXTS4', youtubeStart: 5, youtubeEnd: 15, hint: '퐁당퐁당 돌을 던지자', answers: ['퐁당퐁당', '퐁당퐁당돌을던지자'], difficulty: 1 },
{ id: 'dy005', category: '동요', youtubeId: 'hHBo6QTr2u4', youtubeStart: 5, youtubeEnd: 15, hint: '머리 어깨 무릎 발 무릎 발', answers: ['머리 어깨 무릎 발', '머리어깨무릎발'], difficulty: 1 },
{ id: 'dy006', category: '동요', youtubeId: 'yCjJyiqpAuU', youtubeStart: 5, youtubeEnd: 15, hint: '반짝반짝 작은 별 아름답게 빛나네', answers: ['반짝반짝 작은 별', '작은별', 'twinkle little star'], difficulty: 1 },
{ id: 'dy007', category: '동요', youtubeId: 'yCjJyiqpAuU', youtubeStart: 5, youtubeEnd: 15, hint: '반짝반짝 작은 별 아름답게 빛나네', answers: ['반짝반짝 작은 별', '작은별', 'twinkle little star'], difficulty: 1 },
{ id: 'dy008', category: '동요', youtubeId: 'wEkxfFJeHwI', youtubeStart: 5, youtubeEnd: 15, hint: '봄봄봄 봄이 왔어요', answers: ['봄봄봄', '봄이왔어요'], difficulty: 1 },
{ id: 'dy009', category: '동요', youtubeId: '-KYsZGZHPyU', youtubeStart: 3, youtubeEnd: 13, hint: '학교 종이 땡땡땡 어서 모이자', answers: ['학교 종이 땡땡땡', '학교종이땡땡땡'], difficulty: 1 },
{ id: 'dy010', category: '동요', youtubeId: '2eT2CFSEhFY', youtubeStart: 5, youtubeEnd: 15, hint: '빙고 빙고 빙고 B-I-N-G-O', answers: ['빙고', 'bingo'], difficulty: 1 },
{ id: 'dy011', category: '동요', youtubeId: '761ae_KDg_Q', youtubeStart: 5, youtubeEnd: 15, hint: '아기상어 뚜루루뚜루', answers: ['아기상어', 'baby shark'], difficulty: 1 },
{ id: 'dy012', category: '동요', youtubeId: 'uc5G4iUL6_s', youtubeStart: 5, youtubeEnd: 15, hint: '둥글게 둥글게 둥글게 둥글게', answers: ['둥글게둥글게', '둥글게 둥글게'], difficulty: 1 },
{ id: 'dy013', category: '동요', youtubeId: 'xFDizpyUkgQ', youtubeStart: 5, youtubeEnd: 15, hint: '섬집 아기 엄마가 섬그늘에', answers: ['섬집 아기', '섬집아기'], difficulty: 2 },
{ id: 'dy014', category: '동요', youtubeId: '_ty5RrOrHz8', youtubeStart: 5, youtubeEnd: 15, hint: '파란 마음 하얀 마음', answers: ['파란 마음 하얀 마음', '파란마음하얀마음'], difficulty: 2 },
{ id: 'dy015', category: '동요', youtubeId: 'aHaYIEYn-iU', youtubeStart: 5, youtubeEnd: 15, hint: '꼬끼오 수탉이 울면', answers: ['아침', '아침노래', '닭이울면'], difficulty: 2 },
{ id: 'dy016', category: '동요', youtubeId: 'AaU-GY7RVt8', youtubeStart: 5, youtubeEnd: 15, hint: '열 꼬마 인디언', answers: ['열 꼬마 인디언', '꼬마인디언', 'ten little indians'], difficulty: 1 },
{ id: 'dy017', category: '동요', youtubeId: 'eu89jwQbp0k', youtubeStart: 5, youtubeEnd: 15, hint: '우리 모두 다같이 손뼉을 짝짝짝', answers: ['손뼉을 짝짝짝', '우리모두다같이'], difficulty: 1 },
{ id: 'dy018', category: '동요', youtubeId: 'Vq7l8AApMsA', youtubeStart: 5, youtubeEnd: 15, hint: '무궁화 꽃이 피었습니다', answers: ['무궁화꽃이피었습니다', '무궁화 꽃이 피었습니다'], difficulty: 1 },
{ id: 'dy019', category: '동요', youtubeId: 'Xf5w8beE8Ow', youtubeStart: 3, youtubeEnd: 13, hint: '생일 축하합니다 생일 축하합니다', answers: ['생일 축하합니다', '해피버스데이', 'happy birthday'], difficulty: 1 },
{ id: 'dy020', category: '동요', youtubeId: 'tUoS_Lg__7I', youtubeStart: 5, youtubeEnd: 15, hint: '징글벨 징글벨 징글 올더웨이', answers: ['징글벨', 'jingle bells'], difficulty: 1 },
{ id: 'dy021', category: '동요', youtubeId: 'sv_cKYrt-Qc', youtubeStart: 5, youtubeEnd: 15, hint: '루돌프 사슴코는 매우 반짝이는', answers: ['루돌프 사슴코', '루돌프', 'rudolph'], difficulty: 1 },
{ id: 'dy022', category: '동요', youtubeId: 'dosnQVuYIi0', youtubeStart: 5, youtubeEnd: 15, hint: '나는야 포켓몬 마스터', answers: ['포켓몬스터', '포켓몬', 'pokemon'], difficulty: 1 },
{ id: 'dy023', category: '동요', youtubeId: 'JZjOOv79cfg', youtubeStart: 5, youtubeEnd: 15, hint: '올챙이와 개구리 올챙이 적 생각은 못하고', answers: ['올챙이와 개구리', '올챙이송'], difficulty: 1 },
{ id: 'dy024', category: '동요', youtubeId: '8SeJR-52bbA', youtubeStart: 5, youtubeEnd: 15, hint: '솜사탕 솜사탕 하얀 솜사탕', answers: ['솜사탕', '솜사탕노래'], difficulty: 2 },
{ id: 'dy025', category: '동요', youtubeId: 'UV6x_VMmcrk', youtubeStart: 5, youtubeEnd: 15, hint: '꿀밤을 주면 맛있게 먹을게', answers: ['꿀밤', '도토리'], difficulty: 2 },
{ id: 'dy026', category: '동요', youtubeId: 'gBw1qOCx3Sg', youtubeStart: 5, youtubeEnd: 15, hint: '어린 음악대 나팔을 불며', answers: ['어린 음악대', '어린음악대'], difficulty: 2 },
{ id: 'dy027', category: '동요', youtubeId: 'hsTXCNNq2vE', youtubeStart: 5, youtubeEnd: 15, hint: '우리집에 왜 왔니 왜 왔니 왜 왔니', answers: ['우리집에왜왔니', '우리 집에 왜 왔니'], difficulty: 1 },
{ id: 'dy028', category: '동요', youtubeId: 'C9tH8vrBG2k', youtubeStart: 5, youtubeEnd: 15, hint: '거미가 줄을 타고 올라갑니다', answers: ['거미줄', '거미가줄을타고', 'itsy bitsy spider'], difficulty: 1 },
{ id: 'dy029', category: '동요', youtubeId: 'e_04ZrNroTo', youtubeStart: 5, youtubeEnd: 15, hint: '버스 바퀴는 빙글빙글', answers: ['버스 바퀴는 빙글빙글', 'wheels on the bus'], difficulty: 1 },
{ id: 'dy030', category: '동요', youtubeId: 'yCjJyiqpAuU', youtubeStart: 5, youtubeEnd: 15, hint: '작은 별들이 반짝이는 밤하늘 아래', answers: ['별', '별동요', '밤하늘'], difficulty: 2 },
// ── 클래식 음악 (20개) ────────────────────────────────────
{ id: 'cl001', category: '클래식 음악', youtubeId: 'OV6Lp7cnX7s', youtubeStart: 0, youtubeEnd: 10, hint: '빠바바밤~ 베토벤의 운명', answers: ['운명 교향곡', '베토벤 5번', '운명'], difficulty: 1 },
{ id: 'cl002', category: '클래식 음악', youtubeId: 'GRxofEmo3HA', youtubeStart: 5, youtubeEnd: 15, hint: '비발디의 봄 1악장', answers: ['사계', '비발디 사계', '봄'], difficulty: 1 },
{ id: 'cl003', category: '클래식 음악', youtubeId: 'gFjveJ5sgeQ', youtubeStart: 6, youtubeEnd: 16, hint: '차이콥스키의 호두까기 인형 중 사탕요정의 춤', answers: ['호두까기 인형', '사탕요정의 춤', 'nutcracker'], difficulty: 1 },
{ id: 'cl004', category: '클래식 음악', youtubeId: '2uvMgL4m2Cc', youtubeStart: 8, youtubeEnd: 18, hint: '엘가의 위풍당당 행진곡', answers: ['위풍당당 행진곡', '엘가', 'pomp and circumstance'], difficulty: 1 },
{ id: 'cl005', category: '클래식 음악', youtubeId: 'cJ6gIPLxJ5w', youtubeStart: 0, youtubeEnd: 10, hint: '모차르트의 아이네 클라이네 나흐트무지크', answers: ['아이네 클라이네', '모차르트 세레나데', 'eine kleine nachtmusik'], difficulty: 2 },
{ id: 'cl006', category: '클래식 음악', youtubeId: 'XWOC6xImhtg', youtubeStart: 8, youtubeEnd: 18, hint: '바흐의 G선상의 아리아', answers: ['G선상의 아리아', '바흐 아리아', 'air on g string'], difficulty: 2 },
{ id: 'cl007', category: '클래식 음악', youtubeId: 'jOofzffyDSA', youtubeStart: 60, youtubeEnd: 70, hint: '드보르작 신세계 교향곡 4악장', answers: ['신세계 교향곡', '드보르작 신세계', 'new world symphony'], difficulty: 2 },
{ id: 'cl008', category: '클래식 음악', youtubeId: 'RIck7OCm6UU', youtubeStart: 0, youtubeEnd: 10, hint: '차이콥스키 백조의 호수 테마', answers: ['백조의 호수', 'swan lake'], difficulty: 1 },
{ id: 'cl009', category: '클래식 음악', youtubeId: 'YGRO05WcNDk', youtubeStart: 5, youtubeEnd: 15, hint: '쇼팽의 야상곡(녹턴)', answers: ['녹턴', '야상곡', 'nocturne'], difficulty: 2 },
{ id: 'cl010', category: '클래식 음악', youtubeId: '4LLylhgR3uM', youtubeStart: 5, youtubeEnd: 15, hint: '라벨의 볼레로', answers: ['볼레로', 'bolero'], difficulty: 1 },
{ id: 'cl011', category: '클래식 음악', youtubeId: '4Tr0otuiQuU', youtubeStart: 0, youtubeEnd: 10, hint: '베토벤 월광 소나타 1악장', answers: ['월광 소나타', '월광', 'moonlight sonata'], difficulty: 1 },
{ id: 'cl012', category: '클래식 음악', youtubeId: 'IUZEtVbJT5c', youtubeStart: 20, youtubeEnd: 30, hint: '헨델의 메시아 중 할렐루야', answers: ['할렐루야', 'hallelujah', '헨델 할렐루야'], difficulty: 1 },
{ id: 'cl013', category: '클래식 음악', youtubeId: 'Gus4dnQuiGk', youtubeStart: 0, youtubeEnd: 10, hint: '쇼팽 즉흥 환상곡', answers: ['환상 즉흥곡', '즉흥환상곡', 'fantasie impromptu'], difficulty: 2 },
{ id: 'cl014', category: '클래식 음악', youtubeId: 'wfF0zHeU3Zs', youtubeStart: 0, youtubeEnd: 10, hint: '베토벤 엘리제를 위하여', answers: ['엘리제를 위하여', 'fur elise'], difficulty: 1 },
{ id: 'cl015', category: '클래식 음악', youtubeId: 'hsBt9yZDslA', youtubeStart: 12, youtubeEnd: 22, hint: '슈베르트 아베 마리아', answers: ['아베 마리아', 'ave maria'], difficulty: 1 },
{ id: 'cl016', category: '클래식 음악', youtubeId: 'zWytgJy-u8w', youtubeStart: 30, youtubeEnd: 40, hint: '오펜바흐 캉캉', answers: ['캉캉', 'can can', '오펜바흐'], difficulty: 1 },
{ id: 'cl017', category: '클래식 음악', youtubeId: 'JNbe34V1nog', youtubeStart: 28, youtubeEnd: 38, hint: '파헬벨의 캐논', answers: ['캐논', 'canon', '캐논변주곡'], difficulty: 1 },
{ id: 'cl018', category: '클래식 음악', youtubeId: 'fiOGCwZGgXY', youtubeStart: 60, youtubeEnd: 70, hint: '스메타나 나의 조국 중 몰다우', answers: ['몰다우', 'moldau', '나의조국'], difficulty: 2 },
{ id: 'cl019', category: '클래식 음악', youtubeId: 'NegCKtoRfR8', youtubeStart: 6, youtubeEnd: 16, hint: '생상스 동물의 사육제 중 백조', answers: ['동물의 사육제', '백조', 'carnival of the animals'], difficulty: 2 },
{ id: 'cl020', category: '클래식 음악', youtubeId: 'jxa2er9Y1iU', youtubeStart: 0, youtubeEnd: 10, hint: '무소르그스키 전람회의 그림', answers: ['전람회의 그림', 'pictures at an exhibition'], difficulty: 3 },
// ── 작곡가 (15개) ─────────────────────────────────────────
{ id: 'cp001', category: '작곡가', youtubeId: 'OV6Lp7cnX7s', youtubeStart: 0, youtubeEnd: 10, hint: '운명 교향곡, 월광 소나타를 작곡한 독일 작곡가', answers: ['베토벤', 'beethoven', '루트비히 반 베토벤'], difficulty: 1 },
{ id: 'cp002', category: '작곡가', youtubeId: 'Qb_jQBgzU-I', youtubeStart: 0, youtubeEnd: 10, hint: '피가로의 결혼, 마술피리를 작곡한 신동', answers: ['모차르트', 'mozart', '볼프강 아마데우스 모차르트'], difficulty: 1 },
{ id: 'cp003', category: '작곡가', youtubeId: 'GRxofEmo3HA', youtubeStart: 5, youtubeEnd: 15, hint: '사계를 작곡한 이탈리아 바로크 작곡가', answers: ['비발디', 'vivaldi', '안토니오 비발디'], difficulty: 1 },
{ id: 'cp004', category: '작곡가', youtubeId: '8tpzyYFqJWM', youtubeStart: 0, youtubeEnd: 10, hint: 'G선상의 아리아, 토카타와 푸가를 작곡한 바로크 거장', answers: ['바흐', 'bach', '요한 세바스티안 바흐'], difficulty: 1 },
{ id: 'cp005', category: '작곡가', youtubeId: '192zr438g-k', youtubeStart: 0, youtubeEnd: 10, hint: '환상 즉흥곡, 녹턴을 작곡한 피아노 시인', answers: ['쇼팽', 'chopin', '프레데릭 쇼팽'], difficulty: 1 },
{ id: 'cp006', category: '작곡가', youtubeId: '9cNQFB0TDfY', youtubeStart: 0, youtubeEnd: 10, hint: '백조의 호수, 호두까기 인형을 작곡한 러시아 작곡가', answers: ['차이콥스키', 'tchaikovsky', '표트르 차이콥스키'], difficulty: 1 },
{ id: 'cp007', category: '작곡가', youtubeId: '0FbQZCsYXVg', youtubeStart: 0, youtubeEnd: 10, hint: '헝가리 랩소디를 작곡한 피아노 거장', answers: ['리스트', 'liszt', '프란츠 리스트'], difficulty: 2 },
{ id: 'cp008', category: '작곡가', youtubeId: '5Eqj9G5j1ss', youtubeStart: 0, youtubeEnd: 10, hint: '볼레로를 작곡한 프랑스 작곡가', answers: ['라벨', 'ravel', '모리스 라벨'], difficulty: 2 },
{ id: 'cp009', category: '작곡가', youtubeId: 'L6P3cIJHWjw', youtubeStart: 0, youtubeEnd: 10, hint: '교향시 핀란디아를 작곡한 핀란드 작곡가', answers: ['시벨리우스', 'sibelius', '장 시벨리우스'], difficulty: 3 },
{ id: 'cp010', category: '작곡가', youtubeId: 'jF1OQkHybEQ', youtubeStart: 30, youtubeEnd: 40, hint: '봄의 제전을 작곡한 현대 작곡가', answers: ['스트라빈스키', 'stravinsky', '이고르 스트라빈스키'], difficulty: 2 },
{ id: 'cp011', category: '작곡가', youtubeId: 'XpYGgtrMTYs', youtubeStart: 0, youtubeEnd: 10, hint: '미완성 교향곡을 작곡한 오스트리아 작곡가', answers: ['슈베르트', 'schubert', '프란츠 슈베르트'], difficulty: 2 },
{ id: 'cp012', category: '작곡가', youtubeId: 'jOofzffyDSA', youtubeStart: 60, youtubeEnd: 70, hint: '신세계 교향곡을 작곡한 체코 작곡가', answers: ['드보르작', 'dvorak', '안토닌 드보르작'], difficulty: 2 },
{ id: 'cp013', category: '작곡가', youtubeId: 'K2snTkaD64U', youtubeStart: 0, youtubeEnd: 10, hint: '카르멘을 작곡한 프랑스 오페라 작곡가', answers: ['비제', 'bizet', '조르주 비제'], difficulty: 2 },
{ id: 'cp014', category: '작곡가', youtubeId: 'HqNa9Cpa3L8', youtubeStart: 0, youtubeEnd: 10, hint: '아이다, 오텔로를 작곡한 이탈리아 오페라 작곡가', answers: ['베르디', 'verdi', '주세페 베르디'], difficulty: 2 },
{ id: 'cp015', category: '작곡가', youtubeId: '9ADfSxJ3AFE', youtubeStart: 0, youtubeEnd: 10, hint: '라 트라비아타를 작곡한 이탈리아 작곡가', answers: ['푸치니', 'puccini', '자코모 푸치니'], difficulty: 2 },
// ── 공연 예술 (15개) ─────────────────────────────────────
{ id: 'pa001', category: '공연 예술', youtubeId: 'GqrH1z8L-9Q', youtubeStart: 156, youtubeEnd: 166, hint: '뮤지컬 캣츠의 대표곡 Memory', answers: ['캣츠', 'cats', 'memory'], difficulty: 1 },
{ id: 'pa002', category: '공연 예술', youtubeId: '8J1lmuchz7o', youtubeStart: 73, youtubeEnd: 83, hint: '오페라의 유령 테마곡', answers: ['오페라의 유령', 'phantom of the opera'], difficulty: 1 },
{ id: 'pa003', category: '공연 예술', youtubeId: 'Ojxmk78lMXY', youtubeStart: 158, youtubeEnd: 168, hint: '뮤지컬 레 미제라블의 I Dreamed a Dream', answers: ['레 미제라블', 'les miserables', '레미제라블'], difficulty: 1 },
{ id: 'pa004', category: '공연 예술', youtubeId: 'Do8oqR2TR1M', youtubeStart: 50, youtubeEnd: 60, hint: '뮤지컬 맘마미아의 ABBA 노래', answers: ['맘마미아', 'mamma mia', 'abba'], difficulty: 1 },
{ id: 'pa005', category: '공연 예술', youtubeId: 'GibiNy4d4gc', youtubeStart: 10, youtubeEnd: 20, hint: '뮤지컬 라이온킹 Circle of Life', answers: ['라이온킹', 'lion king', 'circle of life'], difficulty: 1 },
{ id: 'pa006', category: '공연 예술', youtubeId: 'l0Bs_eaXaCo', youtubeStart: 200, youtubeEnd: 210, hint: '뮤지컬 위키드의 Defying Gravity', answers: ['위키드', 'wicked', 'defying gravity'], difficulty: 2 },
{ id: 'pa007', category: '공연 예술', youtubeId: 'VhinPd5RRJw', youtubeStart: 30, youtubeEnd: 40, hint: '뮤지컬 해밀턴의 Alexander Hamilton', answers: ['해밀턴', 'hamilton'], difficulty: 2 },
{ id: 'pa008', category: '공연 예술', youtubeId: 'Le8a7u1pANU', youtubeStart: 75, youtubeEnd: 85, hint: '뮤지컬 시카고의 All That Jazz', answers: ['시카고', 'chicago', 'all that jazz'], difficulty: 2 },
{ id: 'pa009', category: '공연 예술', youtubeId: 'KJ_HHRJf0xg', youtubeStart: 18, youtubeEnd: 28, hint: '오페라 카르멘의 하바네라', answers: ['카르멘', 'carmen', '하바네라'], difficulty: 2 },
{ id: 'pa010', category: '공연 예술', youtubeId: 'SK-NUuTCras', youtubeStart: 12, youtubeEnd: 22, hint: '오페라 라 트라비아타의 축배의 노래', answers: ['라 트라비아타', 'la traviata', '축배의 노래'], difficulty: 2 },
{ id: 'pa011', category: '공연 예술', youtubeId: 'e__Pp4FxsjU', youtubeStart: 65, youtubeEnd: 75, hint: '뮤지컬 그리스의 Summer Nights', answers: ['그리스', 'grease', 'summer nights'], difficulty: 1 },
{ id: 'pa012', category: '공연 예술', youtubeId: 'Qy9cj-zwbVY', youtubeStart: 60, youtubeEnd: 70, hint: '뮤지컬 사운드 오브 뮤직의 Do Re Mi', answers: ['사운드 오브 뮤직', 'sound of music', 'do re mi'], difficulty: 1 },
{ id: 'pa013', category: '공연 예술', youtubeId: '8woil4kgU5Y', youtubeStart: 8, youtubeEnd: 18, hint: '발레 잠자는 숲속의 미녀 테마', answers: ['잠자는 숲속의 미녀', 'sleeping beauty', '차이콥스키 발레'], difficulty: 2 },
{ id: 'pa014', category: '공연 예술', youtubeId: 'FVnxKAoFzBg', youtubeStart: 14, youtubeEnd: 24, hint: '뮤지컬 노트르담 드 파리', answers: ['노트르담 드 파리', 'notre dame de paris', '노트르담'], difficulty: 2 },
{ id: 'pa015', category: '공연 예술', youtubeId: 'rEREXwJ2P9Q', youtubeStart: 70, youtubeEnd: 80, hint: '한국 뮤지컬 명성황후', answers: ['명성황후', '명성황후 뮤지컬'], difficulty: 2 },
// ── 스포츠 (20개) ─────────────────────────────────────────
{ id: 'sp001', category: '스포츠', youtubeId: 'aNxw6hYgBuo', youtubeStart: 0, youtubeEnd: 10, hint: '공이 골대 안으로 들어갈 때 나는 소리', answers: ['골', '축구', '골인'], difficulty: 1 },
{ id: 'sp002', category: '스포츠', youtubeId: 'R4r9lv8MMIw', youtubeStart: 0, youtubeEnd: 10, hint: '야구 방망이로 공을 치는 소리', answers: ['야구', '홈런', '타격'], difficulty: 1 },
{ id: 'sp003', category: '스포츠', youtubeId: 'AxwdDYhphwc', youtubeStart: 0, youtubeEnd: 10, hint: '테니스 라켓이 공을 치는 소리', answers: ['테니스', '테니스경기'], difficulty: 1 },
{ id: 'sp004', category: '스포츠', youtubeId: 'xJLmI99p9TE', youtubeStart: 0, youtubeEnd: 10, hint: '복싱 글러브가 샌드백을 치는 소리', answers: ['복싱', '권투'], difficulty: 1 },
{ id: 'sp005', category: '스포츠', youtubeId: 'c2_bubuML80', youtubeStart: 0, youtubeEnd: 10, hint: '수영 출발 신호음과 물 튀기는 소리', answers: ['수영', '수영경기'], difficulty: 1 },
{ id: 'sp006', category: '스포츠', youtubeId: 'xx-1T7G6hXM', youtubeStart: 0, youtubeEnd: 10, hint: '볼링공이 핀을 쓸어버리는 소리', answers: ['볼링', '스트라이크'], difficulty: 1 },
{ id: 'sp007', category: '스포츠', youtubeId: 'snctOXOfS0M', youtubeStart: 0, youtubeEnd: 10, hint: '농구공이 림을 통과하는 소리', answers: ['농구', '슛', '농구공'], difficulty: 1 },
{ id: 'sp008', category: '스포츠', youtubeId: 'kMr9BbC69PE', youtubeStart: 0, youtubeEnd: 10, hint: '골프 클럽이 공을 치는 소리', answers: ['골프', '골프스윙'], difficulty: 1 },
{ id: 'sp009', category: '스포츠', youtubeId: 'UonuoQY8HHQ', youtubeStart: 0, youtubeEnd: 10, hint: '펜싱 검이 부딪히는 소리', answers: ['펜싱', '검도'], difficulty: 2 },
{ id: 'sp010', category: '스포츠', youtubeId: '2PeVmB0vw4Y', youtubeStart: 0, youtubeEnd: 10, hint: '탁구 공이 테이블에 튀기는 소리', answers: ['탁구', '핑퐁'], difficulty: 1 },
{ id: 'sp011', category: '스포츠', youtubeId: 'xM-TmpbjhcM', youtubeStart: 0, youtubeEnd: 10, hint: '스키 활강 시 바람 가르는 소리', answers: ['스키', '스키점프'], difficulty: 2 },
{ id: 'sp012', category: '스포츠', youtubeId: 'j153SskYTBs', youtubeStart: 30, youtubeEnd: 40, hint: '씨름 선수가 넘어지는 소리', answers: ['씨름', '한국씨름'], difficulty: 2 },
{ id: 'sp013', category: '스포츠', youtubeId: 'pdKOaNwR5es', youtubeStart: 0, youtubeEnd: 10, hint: '태권도 발차기 소리', answers: ['태권도', '태권도발차기'], difficulty: 1 },
{ id: 'sp014', category: '스포츠', youtubeId: 'e8Ryrij3M4s', youtubeStart: 0, youtubeEnd: 10, hint: '양궁 화살이 과녁에 꽂히는 소리', answers: ['양궁', '화살', '궁도'], difficulty: 2 },
{ id: 'sp015', category: '스포츠', youtubeId: '1DbZOyE-WI4', youtubeStart: 0, youtubeEnd: 10, hint: '배드민턴 셔틀콕 치는 소리', answers: ['배드민턴', '셔틀콕'], difficulty: 1 },
{ id: 'sp016', category: '스포츠', youtubeId: 'DIja7Q1o1uQ', youtubeStart: 0, youtubeEnd: 10, hint: '올림픽 시작을 알리는 팡파레', answers: ['올림픽', '올림픽경기'], difficulty: 1 },
{ id: 'sp017', category: '스포츠', youtubeId: 'U2BXgJPNN54', youtubeStart: 0, youtubeEnd: 10, hint: '럭비 선수들이 스크럼을 짜는 소리', answers: ['럭비', '럭비경기'], difficulty: 2 },
{ id: 'sp018', category: '스포츠', youtubeId: 'TecDb2cjd40', youtubeStart: 0, youtubeEnd: 10, hint: '아이스하키 퍽이 골대에 맞는 소리', answers: ['아이스하키', '하키'], difficulty: 2 },
{ id: 'sp019', category: '스포츠', youtubeId: 'r5Qa6vi8fPE', youtubeStart: 0, youtubeEnd: 10, hint: '마라톤 출발 총소리', answers: ['마라톤', '달리기', '출발'], difficulty: 1 },
{ id: 'sp020', category: '스포츠', youtubeId: 'tLYyHgiwSow', youtubeStart: 0, youtubeEnd: 10, hint: '유도 선수가 상대를 메치는 소리', answers: ['유도', '유도경기'], difficulty: 2 },
// ── 운송수단 (20개) ───────────────────────────────────────
{ id: 'tr001', category: '운송수단', youtubeId: 'FGYp1EKz3Bg', youtubeStart: 40, youtubeEnd: 50, hint: '칙칙폭폭 달리는 소리', answers: ['기차', '열차', 'train'], difficulty: 1 },
{ id: 'tr002', category: '운송수단', youtubeId: 'FwZKVPPGfeg', youtubeStart: 0, youtubeEnd: 10, hint: '빠앙 클락션 소리', answers: ['자동차', '차', 'car'], difficulty: 1 },
{ id: 'tr003', category: '운송수단', youtubeId: '5tyANvkpRtQ', youtubeStart: 15, youtubeEnd: 25, hint: '부르릉 오토바이 엔진 소리', answers: ['오토바이', '모터사이클', 'motorcycle'], difficulty: 1 },
{ id: 'tr004', category: '운송수단', youtubeId: 'SG6H25xZ6Z4', youtubeStart: 0, youtubeEnd: 10, hint: '위잉 프로펠러 돌아가는 소리', answers: ['비행기', '항공기', 'airplane'], difficulty: 1 },
{ id: 'tr005', category: '운송수단', youtubeId: 'bn0LS6K2WdU', youtubeStart: 0, youtubeEnd: 10, hint: '뚜뚜뚜 배 경적 소리', answers: ['배', '선박', '여객선'], difficulty: 1 },
{ id: 'tr006', category: '운송수단', youtubeId: 'QLHESVx8jeU', youtubeStart: 0, youtubeEnd: 10, hint: '삐걱삐걱 자전거 페달 밟는 소리', answers: ['자전거', 'bicycle'], difficulty: 1 },
{ id: 'tr007', category: '운송수단', youtubeId: 'VXEGBzxfGKg', youtubeStart: 0, youtubeEnd: 10, hint: '땡땡땡 전차가 달리는 소리', answers: ['트램', '전차', 'tram'], difficulty: 2 },
{ id: 'tr008', category: '운송수단', youtubeId: 'YsJbLdCRN_E', youtubeStart: 0, youtubeEnd: 10, hint: '삐유 소방차 사이렌 소리', answers: ['소방차', '사이렌', '소방서'], difficulty: 1 },
{ id: 'tr009', category: '운송수단', youtubeId: '9GFcMVccOFA', youtubeStart: 0, youtubeEnd: 10, hint: '위이이잉 헬리콥터 날개 소리', answers: ['헬리콥터', 'helicopter'], difficulty: 1 },
{ id: 'tr010', category: '운송수단', youtubeId: '-GkruP6jzXA', youtubeStart: 0, youtubeEnd: 10, hint: '덜컹덜컹 버스가 달리는 소리', answers: ['버스', 'bus'], difficulty: 1 },
{ id: 'tr011', category: '운송수단', youtubeId: '7B2fqDd7pGs', youtubeStart: 0, youtubeEnd: 10, hint: '지하철 문이 열리고 닫히는 소리', answers: ['지하철', '전철', 'subway'], difficulty: 1 },
{ id: 'tr012', category: '운송수단', youtubeId: 'i_nJd44RRyA', youtubeStart: 0, youtubeEnd: 10, hint: '첨벙첨벙 노를 젓는 소리', answers: ['보트', '카누', '노젓기'], difficulty: 2 },
{ id: 'tr013', category: '운송수단', youtubeId: '_4QiWDR_aFQ', youtubeStart: 0, youtubeEnd: 10, hint: '쌩쌩 스케이트보드 바퀴 소리', answers: ['스케이트보드', 'skateboard'], difficulty: 2 },
{ id: 'tr014', category: '운송수단', youtubeId: 'Km5ciJHE9Ew', youtubeStart: 0, youtubeEnd: 10, hint: '부부부 트럭 엔진 소리', answers: ['트럭', '화물차', 'truck'], difficulty: 1 },
{ id: 'tr015', category: '운송수단', youtubeId: 'brEROnzYULo', youtubeStart: 0, youtubeEnd: 10, hint: '우우우 잠수함 소나 소리', answers: ['잠수함', 'submarine'], difficulty: 2 },
{ id: 'tr016', category: '운송수단', youtubeId: 'Gykr291-kvM', youtubeStart: 0, youtubeEnd: 10, hint: '히이잉 말발굽 소리', answers: ['말', '마차', '말발굽'], difficulty: 1 },
{ id: 'tr017', category: '운송수단', youtubeId: 'uz4Z-s00ytI', youtubeStart: 0, youtubeEnd: 10, hint: '쉬이이잉 고속열차 지나가는 소리', answers: ['고속철도', 'KTX', '고속열차'], difficulty: 1 },
{ id: 'tr018', category: '운송수단', youtubeId: 'DUTQkbuzxtk', youtubeStart: 0, youtubeEnd: 10, hint: '붕붕 드론 프로펠러 소리', answers: ['드론', 'drone'], difficulty: 1 },
{ id: 'tr019', category: '운송수단', youtubeId: '7g4CdjwrLcQ', youtubeStart: 0, youtubeEnd: 10, hint: '쿵쿵쿵 굴착기 작동 소리', answers: ['굴착기', '포크레인', '건설차량'], difficulty: 2 },
{ id: 'tr020', category: '운송수단', youtubeId: 'OMY0Z4Rf8D8', youtubeStart: 0, youtubeEnd: 10, hint: '로켓이 발사될 때 나는 폭발음', answers: ['로켓', '우주선', '발사'], difficulty: 1 },
// ── 악기 (25개) ───────────────────────────────────────────
{ id: 'in001', category: '악기', youtubeId: 'hJ6E0OrQ9hs', youtubeStart: 0, youtubeEnd: 10, hint: '건반을 눌러 연주하는 대표 악기', answers: ['피아노', 'piano'], difficulty: 1 },
{ id: 'in002', category: '악기', youtubeId: 'wh-pBxeHE3U', youtubeStart: 0, youtubeEnd: 10, hint: '줄을 활로 문질러 연주하는 악기', answers: ['바이올린', 'violin'], difficulty: 1 },
{ id: 'in003', category: '악기', youtubeId: 'WJrhwZlFjS0', youtubeStart: 10, youtubeEnd: 20, hint: '줄을 손가락으로 퉁기는 기타', answers: ['기타', '어쿠스틱기타', 'guitar'], difficulty: 1 },
{ id: 'in004', category: '악기', youtubeId: '8ouAIpp8nTw', youtubeStart: 10, youtubeEnd: 20, hint: '두드려서 소리 내는 타악기', answers: ['드럼', '북', 'drum'], difficulty: 1 },
{ id: 'in005', category: '악기', youtubeId: 'MDXGKx-E-iE', youtubeStart: 2, youtubeEnd: 12, hint: '입으로 불어 연주하는 금관악기', answers: ['트럼펫', 'trumpet'], difficulty: 1 },
{ id: 'in006', category: '악기', youtubeId: 'FaNWiPLtGgk', youtubeStart: 0, youtubeEnd: 10, hint: '관악기 중 가장 큰 금관악기', answers: ['튜바', 'tuba'], difficulty: 2 },
{ id: 'in007', category: '악기', youtubeId: '5q7YJhVmE08', youtubeStart: 2, youtubeEnd: 12, hint: '낮은 음역의 현악기', answers: ['첼로', 'cello'], difficulty: 1 },
{ id: 'in008', category: '악기', youtubeId: 'RYDQmqsW9tA', youtubeStart: 2, youtubeEnd: 12, hint: '가장 큰 현악기', answers: ['콘트라베이스', '더블베이스', 'double bass'], difficulty: 2 },
{ id: 'in009', category: '악기', youtubeId: 'kSfEDb1cMAw', youtubeStart: 2, youtubeEnd: 12, hint: '나무로 만든 관악기, 오보에와 비슷', answers: ['클라리넷', 'clarinet'], difficulty: 2 },
{ id: 'in010', category: '악기', youtubeId: 'CApE3pUE5nA', youtubeStart: 0, youtubeEnd: 10, hint: '두 개의 막대기로 치는 타악기', answers: ['마라카스', '캐스터네츠', '탬버린'], difficulty: 1 },
{ id: 'in011', category: '악기', youtubeId: 'pob6NbRcmBw', youtubeStart: 10, youtubeEnd: 20, hint: '한국 전통 현악기, 12줄', answers: ['가야금', '거문고'], difficulty: 1 },
{ id: 'in012', category: '악기', youtubeId: 'VjXsIa_I3uk', youtubeStart: 10, youtubeEnd: 20, hint: '피리처럼 생긴 한국 전통 관악기', answers: ['단소', '대금', '피리'], difficulty: 2 },
{ id: 'in013', category: '악기', youtubeId: '9fRXeW9OaJk', youtubeStart: 0, youtubeEnd: 10, hint: '전기로 증폭하는 기타', answers: ['일렉기타', '전기기타', 'electric guitar'], difficulty: 1 },
{ id: 'in014', category: '악기', youtubeId: 'YlI1RaNw51w', youtubeStart: 5, youtubeEnd: 15, hint: '낮은 음을 담당하는 전기 현악기', answers: ['베이스기타', '베이스', 'bass guitar'], difficulty: 1 },
{ id: 'in015', category: '악기', youtubeId: 'lpZiPZwwXhM', youtubeStart: 15, youtubeEnd: 25, hint: '바람을 넣어 연주하는 스코틀랜드 악기', answers: ['백파이프', 'bagpipe'], difficulty: 2 },
{ id: 'in016', category: '악기', youtubeId: '-XAsXmbExkE', youtubeStart: 10, youtubeEnd: 20, hint: '조각된 나무 판을 두드리는 악기', answers: ['실로폰', '마림바', 'xylophone'], difficulty: 1 },
{ id: 'in017', category: '악기', youtubeId: 'FBW9ddMHp7w', youtubeStart: 10, youtubeEnd: 20, hint: '작은 금속 판들을 두드리는 악기', answers: ['글로켄슈필', '철금', 'glockenspiel'], difficulty: 3 },
{ id: 'in018', category: '악기', youtubeId: 'HuxANPsnFoE', youtubeStart: 2, youtubeEnd: 12, hint: '입술을 떨어 소리 내는 금관악기', answers: ['호른', '프렌치호른', 'french horn'], difficulty: 2 },
{ id: 'in019', category: '악기', youtubeId: 'GO60wGdHxgw', youtubeStart: 5, youtubeEnd: 15, hint: '하와이 전통 4줄 현악기', answers: ['우쿨렐레', 'ukulele'], difficulty: 1 },
{ id: 'in020', category: '악기', youtubeId: 'bG-Ml_EN-wU', youtubeStart: 30, youtubeEnd: 40, hint: '여러 음을 동시에 내는 건반 악기', answers: ['오르간', '파이프오르간', 'organ'], difficulty: 1 },
{ id: 'in021', category: '악기', youtubeId: '1iD8PGfmAo8', youtubeStart: 5, youtubeEnd: 15, hint: '입으로 불어 리드를 진동시키는 악기', answers: ['색소폰', 'saxophone'], difficulty: 1 },
{ id: 'in022', category: '악기', youtubeId: 'r7CiRLXHWB4', youtubeStart: 10, youtubeEnd: 20, hint: '줄을 손가락으로 뜯는 악기, 천사의 악기', answers: ['하프', 'harp'], difficulty: 1 },
{ id: 'in023', category: '악기', youtubeId: 'Vb57FCOC7Wk', youtubeStart: 0, youtubeEnd: 10, hint: '흔들어 소리 내는 타악기', answers: ['탬버린', 'tambourine'], difficulty: 1 },
{ id: 'in024', category: '악기', youtubeId: 'nq5IAHSlBmk', youtubeStart: 5, youtubeEnd: 15, hint: '입으로 부는 작은 피리', answers: ['리코더', 'recorder'], difficulty: 1 },
{ id: 'in025', category: '악기', youtubeId: 'HkuYUZlEcng', youtubeStart: 10, youtubeEnd: 20, hint: '중국 전통 2줄 현악기', answers: ['얼후', '이호', 'erhu'], difficulty: 3 },
// ── 동물 (25개) ───────────────────────────────────────────
{ id: 'an101', category: '동물', youtubeId: 'J3Bkd_XFJzY', youtubeStart: 0, youtubeEnd: 10, hint: '야옹야옹 울어요', answers: ['고양이', '냥이', 'cat'], difficulty: 1 },
{ id: 'an102', category: '동물', youtubeId: 'k_u3ZwAjK5Q', youtubeStart: 5, youtubeEnd: 15, hint: '멍멍 짖어요', answers: ['개', '강아지', 'dog'], difficulty: 1 },
{ id: 'an103', category: '동물', youtubeId: '0i0_xXdYh20', youtubeStart: 0, youtubeEnd: 10, hint: '음매 넓은 들판에 서 있어요', answers: ['소', '황소', 'cow'], difficulty: 1 },
{ id: 'an104', category: '동물', youtubeId: '7midkbKf_pc', youtubeStart: 0, youtubeEnd: 10, hint: '꿀꿀 흙 속에서 뒹굴어요', answers: ['돼지', 'pig'], difficulty: 1 },
{ id: 'an105', category: '동물', youtubeId: 'sGdvoq9v2Og', youtubeStart: 3, youtubeEnd: 13, hint: '꼬끼오 새벽을 알려요', answers: ['닭', '수탉', 'rooster', 'chicken'], difficulty: 1 },
{ id: 'an106', category: '동물', youtubeId: 'h_m8EqsraXs', youtubeStart: 5, youtubeEnd: 15, hint: '으르렁 정글의 왕', answers: ['사자', 'lion'], difficulty: 1 },
{ id: 'an107', category: '동물', youtubeId: 'cUOmFsX2cXI', youtubeStart: 0, youtubeEnd: 10, hint: '으르렁 호랑이', answers: ['호랑이', 'tiger'], difficulty: 1 },
{ id: 'an108', category: '동물', youtubeId: 'cnrnkMlw3UM', youtubeStart: 5, youtubeEnd: 15, hint: '코끼리 코를 들어올려요', answers: ['코끼리', 'elephant'], difficulty: 1 },
{ id: 'an109', category: '동물', youtubeId: 'PH7_OHWlXj8', youtubeStart: 3, youtubeEnd: 13, hint: '왜왜왜 원숭이', answers: ['원숭이', 'monkey'], difficulty: 1 },
{ id: 'an110', category: '동물', youtubeId: 'aiYReTzFdcE', youtubeStart: 0, youtubeEnd: 10, hint: '개굴개굴 연못에서 울어요', answers: ['개구리', 'frog'], difficulty: 1 },
{ id: 'an111', category: '동물', youtubeId: '3flILVgNIi0', youtubeStart: 5, youtubeEnd: 15, hint: '꽤꽤 오리가 걸어요', answers: ['오리', 'duck'], difficulty: 1 },
{ id: 'an112', category: '동물', youtubeId: 'qHuLE1A8QXQ', youtubeStart: 5, youtubeEnd: 15, hint: '히이잉 달려요', answers: ['말', 'horse'], difficulty: 1 },
{ id: 'an113', category: '동물', youtubeId: '9BqU-zvYRD4', youtubeStart: 5, youtubeEnd: 15, hint: '뻐꾹뻐꾹 숲에서 울어요', answers: ['뻐꾸기', 'cuckoo'], difficulty: 1 },
{ id: 'an114', category: '동물', youtubeId: 'xsQNzzjd0_k', youtubeStart: 3, youtubeEnd: 13, hint: '찍찍찍 쥐가 나타나요', answers: ['쥐', 'mouse', 'rat'], difficulty: 1 },
{ id: 'an115', category: '동물', youtubeId: 'thbgObpfoNs', youtubeStart: 5, youtubeEnd: 15, hint: '맴맴맴 여름을 알려요', answers: ['매미', 'cicada'], difficulty: 1 },
{ id: 'an116', category: '동물', youtubeId: 'ktE_XFhEzpM', youtubeStart: 0, youtubeEnd: 10, hint: '귀뚤귀뚤 가을밤 소리', answers: ['귀뚜라미', 'cricket'], difficulty: 1 },
{ id: 'an117', category: '동물', youtubeId: 'FoUtYfKrT_Q', youtubeStart: 3, youtubeEnd: 13, hint: '꽥꽥 거위가 목을 빼요', answers: ['거위', '오리', 'goose'], difficulty: 1 },
{ id: 'an118', category: '동물', youtubeId: 'Z3APDjieGtk', youtubeStart: 5, youtubeEnd: 15, hint: '부엉부엉 밤에 울어요', answers: ['부엉이', '올빼미', 'owl'], difficulty: 1 },
{ id: 'an119', category: '동물', youtubeId: 'a9gtXvPg5H8', youtubeStart: 2, youtubeEnd: 12, hint: '메에에 산에서 뛰어요', answers: ['염소', '양', 'goat'], difficulty: 1 },
{ id: 'an120', category: '동물', youtubeId: 'CL07hP4C-Tc', youtubeStart: 3, youtubeEnd: 13, hint: '꿀벌이 윙윙 꿀을 따요', answers: ['벌', '꿀벌', 'bee'], difficulty: 1 },
{ id: 'an121', category: '동물', youtubeId: 'wb6Ncu5XhHM', youtubeStart: 0, youtubeEnd: 10, hint: '앵무새가 말을 해요', answers: ['앵무새', 'parrot'], difficulty: 1 },
{ id: 'an122', category: '동물', youtubeId: 'D9OMJjuxATE', youtubeStart: 5, youtubeEnd: 15, hint: '늑대가 달을 보며 울어요', answers: ['늑대', 'wolf'], difficulty: 1 },
{ id: 'an123', category: '동물', youtubeId: 'ZiSssx7kLqA', youtubeStart: 0, youtubeEnd: 10, hint: '물속에서 노래해요 돌고래', answers: ['돌고래', 'dolphin'], difficulty: 1 },
{ id: 'an124', category: '동물', youtubeId: 'ItlB9loeGGg', youtubeStart: 3, youtubeEnd: 13, hint: '고래 숨구멍으로 물을 뿜어요', answers: ['고래', 'whale'], difficulty: 1 },
{ id: 'an125', category: '동물', youtubeId: '_IqZTwcPhhM', youtubeStart: 5, youtubeEnd: 15, hint: '딱따구리가 나무를 쪼아요', answers: ['딱따구리', 'woodpecker'], difficulty: 2 },
// ── 계절 (10개) ───────────────────────────────────────────
{ id: 'se001', category: '계절', youtubeId: 'd_Ft0y2-G5Q', youtubeStart: 30, youtubeEnd: 40, hint: '꽃이 피고 새가 우는 계절', answers: ['봄', 'spring'], difficulty: 1 },
{ id: 'se002', category: '계절', youtubeId: 'y2Z74yuTVAo', youtubeStart: 60, youtubeEnd: 70, hint: '매미가 울고 바다에 가는 계절', answers: ['여름', 'summer'], difficulty: 1 },
{ id: 'se003', category: '계절', youtubeId: 'jFTHmtjxb2g', youtubeStart: 30, youtubeEnd: 40, hint: '낙엽이 지고 귀뚜라미 우는 계절', answers: ['가을', 'autumn', 'fall'], difficulty: 1 },
{ id: 'se004', category: '계절', youtubeId: 'm044HatlZzg', youtubeStart: 20, youtubeEnd: 30, hint: '눈이 내리고 썰매를 타는 계절', answers: ['겨울', 'winter'], difficulty: 1 },
{ id: 'se005', category: '계절', youtubeId: 'XiWffO2fAGs', youtubeStart: 30, youtubeEnd: 40, hint: '봄꽃 축제, 벚꽃이 피는 시기', answers: ['봄', '봄철', 'spring'], difficulty: 1 },
{ id: 'se006', category: '계절', youtubeId: 'WHPEKLQID4U', youtubeStart: 200, youtubeEnd: 210, hint: '장마와 폭염, 해수욕장의 계절', answers: ['여름', 'summer'], difficulty: 1 },
{ id: 'se007', category: '계절', youtubeId: 'xc_FZB_9a1U', youtubeStart: 30, youtubeEnd: 40, hint: '단풍과 추석의 계절', answers: ['가을', 'autumn'], difficulty: 1 },
{ id: 'se008', category: '계절', youtubeId: 'EGerKROL0rk', youtubeStart: 120, youtubeEnd: 130, hint: '크리스마스와 눈싸움의 계절', answers: ['겨울', 'winter'], difficulty: 1 },
{ id: 'se009', category: '계절', youtubeId: 'uLz6drv0-gA', youtubeStart: 30, youtubeEnd: 40, hint: '개나리 진달래 피는 시기', answers: ['봄', 'spring', '이른봄'], difficulty: 1 },
{ id: 'se010', category: '계절', youtubeId: '5XUIab0asws', youtubeStart: 5, youtubeEnd: 15, hint: '첫눈이 내리는 계절', answers: ['겨울', '초겨울', 'winter'], difficulty: 1 },
// ── 자연현상 (15개) ───────────────────────────────────────
{ id: 'nt001', category: '자연현상', youtubeId: 'gVKEM4K8J8A', youtubeStart: 60, youtubeEnd: 70, hint: '우르르 쾅쾅 하늘이 울어요', answers: ['천둥', '번개', 'thunder'], difficulty: 1 },
{ id: 'nt002', category: '자연현상', youtubeId: 'VGq0wZBbOG0', youtubeStart: 120, youtubeEnd: 130, hint: '주룩주룩 내려요', answers: ['비', '빗소리', 'rain'], difficulty: 1 },
{ id: 'nt003', category: '자연현상', youtubeId: 'lWULd19LvaY', youtubeStart: 60, youtubeEnd: 70, hint: '솔솔솔 나뭇잎을 흔들어요', answers: ['바람', 'wind'], difficulty: 1 },
{ id: 'nt004', category: '자연현상', youtubeId: 'WHPEKLQID4U', youtubeStart: 120, youtubeEnd: 130, hint: '파도가 철썩철썩', answers: ['파도', '바다', 'wave'], difficulty: 1 },
{ id: 'nt005', category: '자연현상', youtubeId: 'UNSKJC2yv6I', youtubeStart: 60, youtubeEnd: 70, hint: '졸졸졸 맑은 물이 흘러요', answers: ['시냇물', '개울', '강'], difficulty: 1 },
{ id: 'nt006', category: '자연현상', youtubeId: 'mgLBmLoL2Aw', youtubeStart: 5, youtubeEnd: 15, hint: '우르르 땅이 흔들려요', answers: ['지진', '지진소리', 'earthquake'], difficulty: 1 },
{ id: 'nt007', category: '자연현상', youtubeId: 'n5DZvuB3UBM', youtubeStart: 5, youtubeEnd: 15, hint: '폭발하는 산', answers: ['화산', '화산폭발', 'volcano'], difficulty: 1 },
{ id: 'nt008', category: '자연현상', youtubeId: '4BrvMGznLTo', youtubeStart: 60, youtubeEnd: 70, hint: '쏴아아 폭포가 떨어져요', answers: ['폭포', 'waterfall'], difficulty: 1 },
{ id: 'nt009', category: '자연현상', youtubeId: 'YkWMXfEoLq0', youtubeStart: 60, youtubeEnd: 70, hint: '윙윙 강한 바람이 돌아요', answers: ['태풍', '토네이도', 'typhoon'], difficulty: 1 },
{ id: 'nt010', category: '자연현상', youtubeId: 'm044HatlZzg', youtubeStart: 5, youtubeEnd: 15, hint: '사각사각 눈이 내려요', answers: ['눈', '눈소리', 'snow'], difficulty: 1 },
{ id: 'nt011', category: '자연현상', youtubeId: 'ujBhEF_j9Ls', youtubeStart: 30, youtubeEnd: 40, hint: '탁탁탁 우박이 창문을 두드려요', answers: ['우박', 'hail'], difficulty: 2 },
{ id: 'nt012', category: '자연현상', youtubeId: 'NEOvz3k9DuQ', youtubeStart: 120, youtubeEnd: 130, hint: '모래가 날리는 황사', answers: ['황사', '모래바람', 'sandstorm'], difficulty: 2 },
{ id: 'nt013', category: '자연현상', youtubeId: 'lWULd19LvaY', youtubeStart: 200, youtubeEnd: 210, hint: '안개 낀 아침 조용한 소리', answers: ['안개', 'fog'], difficulty: 2 },
{ id: 'nt014', category: '자연현상', youtubeId: 'sJXo18esnIg', youtubeStart: 30, youtubeEnd: 40, hint: '뚝뚝뚝 처마 끝에서 떨어져요', answers: ['처마', '낙숫물', '빗물'], difficulty: 2 },
{ id: 'nt015', category: '자연현상', youtubeId: 'AyFeUjCC_9Y', youtubeStart: 5, youtubeEnd: 15, hint: '바다 위에서 소용돌이치는 것', answers: ['해일', '쓰나미', 'tsunami'], difficulty: 2 },
// ── 불쾌한 소리 (15개) ────────────────────────────────────
{ id: 'ug001', category: '불쾌한 소리', youtubeId: 'Uv0e02DSuA0', youtubeStart: 0, youtubeEnd: 10, hint: '칠판을 손톱으로 긁는 소리', answers: ['칠판긁는소리', '손톱칠판', '칠판소리'], difficulty: 1 },
{ id: 'ug002', category: '불쾌한 소리', youtubeId: 'j5a0W0UqIPk', youtubeStart: 30, youtubeEnd: 40, hint: '아기가 밤새 우는 소리', answers: ['아기울음', '아기울음소리', '갓난아기'], difficulty: 1 },
{ id: 'ug003', category: '불쾌한 소리', youtubeId: 'FI4eKrSLJCE', youtubeStart: 0, youtubeEnd: 10, hint: '콧물 풀 때 요란하게', answers: ['코푸는소리', '콧물', '코풀기'], difficulty: 1 },
{ id: 'ug004', category: '불쾌한 소리', youtubeId: 'V65PJnRnr4o', youtubeStart: 5, youtubeEnd: 15, hint: '음식 씹을 때 쩝쩝소리', answers: ['쩝쩝소리', '쩝쩝', '식사소리'], difficulty: 1 },
{ id: 'ug005', category: '불쾌한 소리', youtubeId: 'YAvo0X03uRE', youtubeStart: 0, youtubeEnd: 10, hint: '에취 재채기 소리', answers: ['재채기', '기침', '에취'], difficulty: 1 },
{ id: 'ug006', category: '불쾌한 소리', youtubeId: 'ZBKSMqEzIpE', youtubeStart: 0, youtubeEnd: 10, hint: '꼬르륵 배에서 나는 소리', answers: ['배꼬르륵', '배고픔소리', '위장소리'], difficulty: 1 },
{ id: 'ug007', category: '불쾌한 소리', youtubeId: 'COaFOK0U0rU', youtubeStart: 0, youtubeEnd: 10, hint: '모기가 윙윙 날아다니는 소리', answers: ['모기', '모기소리', 'mosquito'], difficulty: 1 },
{ id: 'ug008', category: '불쾌한 소리', youtubeId: 'E7SbmU1yFB4', youtubeStart: 0, youtubeEnd: 10, hint: '삐이이이 귀에 박히는 소음', answers: ['하울링', '마이크하울링', '귀울림'], difficulty: 2 },
{ id: 'ug009', category: '불쾌한 소리', youtubeId: 'WPRJqHGJbnU', youtubeStart: 5, youtubeEnd: 15, hint: '드릴로 벽을 뚫는 공사 소리', answers: ['드릴소리', '공사소리', '착암기'], difficulty: 1 },
{ id: 'ug010', category: '불쾌한 소리', youtubeId: 'lPiXeZkSX54', youtubeStart: 0, youtubeEnd: 10, hint: '옆 집에서 들리는 쿵쿵 발소리', answers: ['층간소음', '발소리', '쿵쿵소리'], difficulty: 1 },
{ id: 'ug011', category: '불쾌한 소리', youtubeId: 'KCZGO32QB1U', youtubeStart: 0, youtubeEnd: 10, hint: '트림 소리', answers: ['트림', '트림소리', 'burp'], difficulty: 1 },
{ id: 'ug012', category: '불쾌한 소리', youtubeId: '7Og1aItvVac', youtubeStart: 0, youtubeEnd: 10, hint: '목이 쉬어서 나는 긁히는 소리', answers: ['목쉰소리', '쉰목소리', '목이쉬는소리'], difficulty: 2 },
{ id: 'ug013', category: '불쾌한 소리', youtubeId: 'dirG2XTAdOU', youtubeStart: 5, youtubeEnd: 15, hint: '형광등이 깜빡이며 내는 소리', answers: ['형광등소리', '전등소음', '조명소음'], difficulty: 2 },
{ id: 'ug014', category: '불쾌한 소리', youtubeId: '_4AGeFZQ6io', youtubeStart: 0, youtubeEnd: 10, hint: '이갈이 소리', answers: ['이갈이', '이빨가는소리', '수면이갈이'], difficulty: 2 },
{ id: 'ug015', category: '불쾌한 소리', youtubeId: 'I7u16bjq5lQ', youtubeStart: 30, youtubeEnd: 40, hint: '스티로폼 자르는 소리', answers: ['스티로폼소리', '스티로폼자르기', '발포스티렌'], difficulty: 1 },
// ── 직업 (15개) ───────────────────────────────────────────
{ id: 'jb001', category: '직업', youtubeId: 'yEb4kojtVHw', youtubeStart: 30, youtubeEnd: 40, hint: '환자를 치료하는 사람', answers: ['의사', '닥터', 'doctor'], difficulty: 1 },
{ id: 'jb002', category: '직업', youtubeId: 'YsJbLdCRN_E', youtubeStart: 5, youtubeEnd: 15, hint: '불을 끄는 사람', answers: ['소방관', '소방사', 'firefighter'], difficulty: 1 },
{ id: 'jb003', category: '직업', youtubeId: 'SG6H25xZ6Z4', youtubeStart: 5, youtubeEnd: 15, hint: '비행기를 모는 사람', answers: ['파일럿', '조종사', 'pilot'], difficulty: 1 },
{ id: 'jb004', category: '직업', youtubeId: 'xDStrQZbxdw', youtubeStart: 5, youtubeEnd: 15, hint: '음식을 만드는 사람', answers: ['요리사', '셰프', 'chef'], difficulty: 1 },
{ id: 'jb005', category: '직업', youtubeId: 'HKieGUH9pzg', youtubeStart: 3, youtubeEnd: 13, hint: '법을 집행하는 사람', answers: ['경찰', '경찰관', 'police'], difficulty: 1 },
{ id: 'jb006', category: '직업', youtubeId: 'PsQkvxfEwkk', youtubeStart: 10, youtubeEnd: 20, hint: '건물을 짓는 사람', answers: ['건축가', '건설노동자', 'builder'], difficulty: 1 },
{ id: 'jb007', category: '직업', youtubeId: 'gC_VkZeNywM', youtubeStart: 0, youtubeEnd: 10, hint: '아이들을 가르치는 사람', answers: ['선생님', '교사', 'teacher'], difficulty: 1 },
{ id: 'jb008', category: '직업', youtubeId: 'OMY0Z4Rf8D8', youtubeStart: 5, youtubeEnd: 15, hint: '우주를 탐험하는 사람', answers: ['우주비행사', '우주인', 'astronaut'], difficulty: 1 },
{ id: 'jb009', category: '직업', youtubeId: 'gNw50HGCNJQ', youtubeStart: 40, youtubeEnd: 50, hint: '물고기를 잡는 사람', answers: ['어부', '어선선원', 'fisherman'], difficulty: 1 },
{ id: 'jb010', category: '직업', youtubeId: '7Otm1vm8BMw', youtubeStart: 0, youtubeEnd: 10, hint: '재판을 진행하는 사람', answers: ['판사', 'judge'], difficulty: 2 },
{ id: 'jb011', category: '직업', youtubeId: 'J3Bkd_XFJzY', youtubeStart: 10, youtubeEnd: 20, hint: '아픈 동물을 치료하는 사람', answers: ['수의사', 'vet', '동물의사'], difficulty: 1 },
{ id: 'jb012', category: '직업', youtubeId: 'gNw50HGCNJQ', youtubeStart: 50, youtubeEnd: 60, hint: '배를 운전하는 사람', answers: ['선장', '항해사', 'captain'], difficulty: 1 },
{ id: 'jb013', category: '직업', youtubeId: 'PsQkvxfEwkk', youtubeStart: 30, youtubeEnd: 40, hint: '광산에서 일하는 사람', answers: ['광부', '광산노동자', 'miner'], difficulty: 2 },
{ id: 'jb014', category: '직업', youtubeId: 'NYHzq7VnUJE', youtubeStart: 0, youtubeEnd: 10, hint: '사진을 찍는 사람', answers: ['사진작가', '포토그래퍼', 'photographer'], difficulty: 1 },
{ id: 'jb015', category: '직업', youtubeId: 'dtn_hy6BHhk', youtubeStart: 0, youtubeEnd: 10, hint: '뉴스를 전달하는 사람', answers: ['아나운서', '기자', '뉴스앵커'], difficulty: 1 },
// ── 물건/장소 (20개) ─────────────────────────────────────
{ id: 'pl001', category: '물건/장소', youtubeId: 'K7jPUJDmWa0', youtubeStart: 1, youtubeEnd: 11, hint: '딩동 문 벨 소리', answers: ['초인종', '도어벨', '벨'], difficulty: 1 },
{ id: 'pl002', category: '물건/장소', youtubeId: 'smOywWXIxC8', youtubeStart: 2, youtubeEnd: 12, hint: '따르릉 자명종이 울리는 소리', answers: ['자명종', '알람', '시계알람'], difficulty: 1 },
{ id: 'pl003', category: '물건/장소', youtubeId: 'TcnufvBffcY', youtubeStart: 2, youtubeEnd: 12, hint: '쨍그랑 유리가 깨지는 소리', answers: ['유리', '유리컵', '창문'], difficulty: 1 },
{ id: 'pl004', category: '물건/장소', youtubeId: 'xDStrQZbxdw', youtubeStart: 3, youtubeEnd: 13, hint: '지글지글 프라이팬에 굽는 소리', answers: ['프라이팬', '요리', '계란프라이'], difficulty: 1 },
{ id: 'pl005', category: '물건/장소', youtubeId: '2BUNHd7ENZk', youtubeStart: 2, youtubeEnd: 12, hint: '딸칵 키보드 타자 소리', answers: ['키보드', '타자기', '컴퓨터'], difficulty: 1 },
{ id: 'pl006', category: '물건/장소', youtubeId: 'R7hn54SRPOk', youtubeStart: 2, youtubeEnd: 12, hint: '와르르 슈퍼마켓 쇼핑카트 소리', answers: ['쇼핑카트', '마트', '슈퍼마켓'], difficulty: 2 },
{ id: 'pl007', category: '물건/장소', youtubeId: 'NWRMaF9PlnY', youtubeStart: 5, youtubeEnd: 15, hint: '콸콸콸 세탁기 돌아가는 소리', answers: ['세탁기', 'washing machine'], difficulty: 1 },
{ id: 'pl008', category: '물건/장소', youtubeId: 'CCWOPKNAVxE', youtubeStart: 3, youtubeEnd: 13, hint: '윙윙 믹서기 소리', answers: ['믹서기', '블렌더', 'blender'], difficulty: 1 },
{ id: 'pl009', category: '물건/장소', youtubeId: 'HWvf-ey2ZGA', youtubeStart: 1, youtubeEnd: 11, hint: '딩~ 전자레인지 완료 소리', answers: ['전자레인지', '전레', 'microwave'], difficulty: 1 },
{ id: 'pl010', category: '물건/장소', youtubeId: 'ao8CNQ4exjg', youtubeStart: 3, youtubeEnd: 13, hint: '톡톡 나무 도마 위에서 써는 소리', answers: ['도마', '주방', '요리'], difficulty: 1 },
{ id: 'pl011', category: '물건/장소', youtubeId: 'iMI6yys_yKo', youtubeStart: 1, youtubeEnd: 11, hint: '찰칵 카메라 셔터 소리', answers: ['카메라', '사진', '셔터'], difficulty: 1 },
{ id: 'pl012', category: '물건/장소', youtubeId: '7Q_oQmRJvtk', youtubeStart: 3, youtubeEnd: 13, hint: '삑삑 계산대 바코드 소리', answers: ['계산대', '마트계산대', '바코드'], difficulty: 1 },
{ id: 'pl013', category: '물건/장소', youtubeId: '5Vty53kgTeU', youtubeStart: 2, youtubeEnd: 12, hint: '땡땡 교회 종소리', answers: ['교회', '성당', '종소리'], difficulty: 1 },
{ id: 'pl014', category: '물건/장소', youtubeId: 'c2_bubuML80', youtubeStart: 5, youtubeEnd: 15, hint: '첨벙 수영장에 뛰어드는 소리', answers: ['수영장', '풀장', 'swimming pool'], difficulty: 1 },
{ id: 'pl015', category: '물건/장소', youtubeId: 'qRMCDFlgO6s', youtubeStart: 3, youtubeEnd: 13, hint: '쌩쌩 선풍기 바람 소리', answers: ['선풍기', '부채', 'fan'], difficulty: 1 },
{ id: 'pl016', category: '물건/장소', youtubeId: 'isOt4KNULqo', youtubeStart: 3, youtubeEnd: 13, hint: '부르릉 청소기 소리', answers: ['청소기', '진공청소기', 'vacuum'], difficulty: 1 },
{ id: 'pl017', category: '물건/장소', youtubeId: 'EeTbd_DIioM', youtubeStart: 5, youtubeEnd: 15, hint: '뻥 팝콘 터지는 소리', answers: ['팝콘', '영화관', 'popcorn'], difficulty: 1 },
{ id: 'pl018', category: '물건/장소', youtubeId: 'aR-hd2OALE8', youtubeStart: 1, youtubeEnd: 11, hint: '딸랑딸랑 아기 장난감 소리', answers: ['아기장난감', '딸랑이', '유아장난감'], difficulty: 1 },
{ id: 'pl019', category: '물건/장소', youtubeId: 'y5Mw0O0BdwU', youtubeStart: 3, youtubeEnd: 13, hint: '뚝딱뚝딱 망치 소리', answers: ['망치', '공사장', '목수'], difficulty: 1 },
{ id: 'pl020', category: '물건/장소', youtubeId: '7B2fqDd7pGs', youtubeStart: 10, youtubeEnd: 20, hint: '철컹철컹 기차역 개찰구 소리', answers: ['기차역', '지하철역', '개찰구'], difficulty: 2 },
// ── 나라 (20개) ───────────────────────────────────────────
{ id: 'cn001', category: '나라', youtubeId: 'dSxGr2dNOfI', youtubeStart: 0, youtubeEnd: 10, hint: '애국가가 울려 퍼지는 나라', answers: ['한국', '대한민국', 'korea'], difficulty: 1 },
{ id: 'cn002', category: '나라', youtubeId: '72dH4YK6TLQ', youtubeStart: 0, youtubeEnd: 10, hint: '기미가요 국가가 울리는 나라', answers: ['일본', 'japan'], difficulty: 1 },
{ id: 'cn003', category: '나라', youtubeId: 'TuHOBjKueKs', youtubeStart: 0, youtubeEnd: 10, hint: '의용군행진곡이 국가인 나라', answers: ['중국', 'china'], difficulty: 1 },
{ id: 'cn004', category: '나라', youtubeId: 'DADmZdbQ9x8', youtubeStart: 0, youtubeEnd: 10, hint: '성조기여 영원하라의 나라', answers: ['미국', '미합중국', 'usa', 'america'], difficulty: 1 },
{ id: 'cn005', category: '나라', youtubeId: 'XZGRxn9eCxU', youtubeStart: 0, youtubeEnd: 10, hint: '갓세이브더킹의 나라', answers: ['영국', 'uk', 'england', '잉글랜드'], difficulty: 1 },
{ id: 'cn006', category: '나라', youtubeId: '215W-29Gt7s', youtubeStart: 0, youtubeEnd: 10, hint: '라 마르세예즈의 나라', answers: ['프랑스', 'france'], difficulty: 1 },
{ id: 'cn007', category: '나라', youtubeId: 'hrSOx1bBmiA', youtubeStart: 0, youtubeEnd: 10, hint: '도이칠란트 위버 알레스의 나라', answers: ['독일', 'germany'], difficulty: 1 },
{ id: 'cn008', category: '나라', youtubeId: '7lc9bcN7ecQ', youtubeStart: 0, youtubeEnd: 10, hint: '삼바 음악의 나라', answers: ['브라질', 'brazil'], difficulty: 1 },
{ id: 'cn009', category: '나라', youtubeId: 'yqBC3l7i7dk', youtubeStart: 0, youtubeEnd: 10, hint: '탱고의 발상지', answers: ['아르헨티나', 'argentina'], difficulty: 1 },
{ id: 'cn010', category: '나라', youtubeId: 'KALktXqhcGU', youtubeStart: 0, youtubeEnd: 10, hint: '플라멩코의 나라', answers: ['스페인', 'spain'], difficulty: 1 },
{ id: 'cn011', category: '나라', youtubeId: 'zwDvF0NtgdU', youtubeStart: 0, youtubeEnd: 10, hint: '오 캐나다의 나라', answers: ['캐나다', 'canada'], difficulty: 1 },
{ id: 'cn012', category: '나라', youtubeId: 'Dqtkckl6s5Y', youtubeStart: 0, youtubeEnd: 10, hint: '어드밴스 오스트레일리아 페어의 나라', answers: ['호주', '오스트레일리아', 'australia'], difficulty: 1 },
{ id: 'cn013', category: '나라', youtubeId: 'RS8KdQi1GRk', youtubeStart: 0, youtubeEnd: 10, hint: '칸조네의 나라', answers: ['이탈리아', 'italy'], difficulty: 1 },
{ id: 'cn014', category: '나라', youtubeId: 'HjixLT6DX7M', youtubeStart: 0, youtubeEnd: 10, hint: '볼쇼이발레단의 나라', answers: ['러시아', 'russia'], difficulty: 1 },
{ id: 'cn015', category: '나라', youtubeId: 'HtMF973tXIY', youtubeStart: 0, youtubeEnd: 10, hint: '인도 전통음악 시타르의 나라', answers: ['인도', 'india'], difficulty: 1 },
{ id: 'cn016', category: '나라', youtubeId: 'jazh7NUZdWE', youtubeStart: 0, youtubeEnd: 10, hint: '북아프리카 사막의 나라 피라미드', answers: ['이집트', 'egypt'], difficulty: 1 },
{ id: 'cn017', category: '나라', youtubeId: '72dH4YK6TLQ', youtubeStart: 5, youtubeEnd: 15, hint: '게이샤와 닌자의 이미지', answers: ['일본', 'japan'], difficulty: 1 },
{ id: 'cn018', category: '나라', youtubeId: 'sNHIwYhwx-Y', youtubeStart: 0, youtubeEnd: 10, hint: '튤립과 풍차의 나라', answers: ['네덜란드', 'netherlands', '홀란드'], difficulty: 1 },
{ id: 'cn019', category: '나라', youtubeId: '215W-29Gt7s', youtubeStart: 5, youtubeEnd: 15, hint: '바게트와 에펠탑의 나라', answers: ['프랑스', 'france'], difficulty: 1 },
{ id: 'cn020', category: '나라', youtubeId: 'dSxGr2dNOfI', youtubeStart: 5, youtubeEnd: 15, hint: '케이팝의 나라', answers: ['한국', '대한민국', 'korea'], difficulty: 1 },
// ── 언어 (15개) ───────────────────────────────────────────
{ id: 'lg001', category: '언어', youtubeId: 'dSxGr2dNOfI', youtubeStart: 10, youtubeEnd: 20, hint: '안녕하세요가 인사인 언어', answers: ['한국어', '한국말', 'korean'], difficulty: 1 },
{ id: 'lg002', category: '언어', youtubeId: 'DADmZdbQ9x8', youtubeStart: 5, youtubeEnd: 15, hint: 'Hello가 인사인 언어', answers: ['영어', 'english'], difficulty: 1 },
{ id: 'lg003', category: '언어', youtubeId: '215W-29Gt7s', youtubeStart: 10, youtubeEnd: 20, hint: 'Bonjour가 인사인 언어', answers: ['프랑스어', 'french', '불어'], difficulty: 1 },
{ id: 'lg004', category: '언어', youtubeId: '72dH4YK6TLQ', youtubeStart: 10, youtubeEnd: 20, hint: 'こんにちは가 인사인 언어', answers: ['일본어', 'japanese'], difficulty: 1 },
{ id: 'lg005', category: '언어', youtubeId: 'TuHOBjKueKs', youtubeStart: 5, youtubeEnd: 15, hint: '你好가 인사인 언어', answers: ['중국어', '만다린', 'chinese', 'mandarin'], difficulty: 1 },
{ id: 'lg006', category: '언어', youtubeId: 'KALktXqhcGU', youtubeStart: 5, youtubeEnd: 15, hint: 'Hola가 인사인 언어', answers: ['스페인어', 'spanish'], difficulty: 1 },
{ id: 'lg007', category: '언어', youtubeId: 'RS8KdQi1GRk', youtubeStart: 5, youtubeEnd: 15, hint: 'Ciao가 인사인 언어', answers: ['이탈리아어', 'italian'], difficulty: 1 },
{ id: 'lg008', category: '언어', youtubeId: 'hrSOx1bBmiA', youtubeStart: 5, youtubeEnd: 15, hint: 'Guten Tag이 인사인 언어', answers: ['독일어', 'german'], difficulty: 1 },
{ id: 'lg009', category: '언어', youtubeId: 'HjixLT6DX7M', youtubeStart: 5, youtubeEnd: 15, hint: 'Привет이 인사인 언어', answers: ['러시아어', 'russian'], difficulty: 2 },
{ id: 'lg010', category: '언어', youtubeId: '9nyixqCm7GU', youtubeStart: 0, youtubeEnd: 10, hint: 'مرحبا이 인사인 언어', answers: ['아랍어', 'arabic'], difficulty: 2 },
{ id: 'lg011', category: '언어', youtubeId: '7lc9bcN7ecQ', youtubeStart: 5, youtubeEnd: 15, hint: 'Olá가 인사인 언어', answers: ['포르투갈어', 'portuguese'], difficulty: 2 },
{ id: 'lg012', category: '언어', youtubeId: 'HtMF973tXIY', youtubeStart: 5, youtubeEnd: 15, hint: 'Namaste가 인사인 언어', answers: ['힌디어', '힌두어', 'hindi'], difficulty: 2 },
{ id: 'lg013', category: '언어', youtubeId: 'XpipI_RasR0', youtubeStart: 0, youtubeEnd: 10, hint: 'สวัสดี가 인사인 언어', answers: ['태국어', 'thai'], difficulty: 2 },
{ id: 'lg014', category: '언어', youtubeId: 'YR0MpZ1vH_s', youtubeStart: 0, youtubeEnd: 10, hint: 'Xin chào가 인사인 언어', answers: ['베트남어', 'vietnamese'], difficulty: 2 },
{ id: 'lg015', category: '언어', youtubeId: '4tE-dVXRdT0', youtubeStart: 20, youtubeEnd: 30, hint: 'Merhaba가 인사인 언어', answers: ['터키어', 'turkish'], difficulty: 2 },
// ── 춤의 종류 (15개) ─────────────────────────────────────
{ id: 'dn001', category: '춤의 종류', youtubeId: 'Gcxv7i02lXc', youtubeStart: 15, youtubeEnd: 25, hint: '아르헨티나 정열의 2인무', answers: ['탱고', 'tango'], difficulty: 1 },
{ id: 'dn002', category: '춤의 종류', youtubeId: 'lXKxmqV86OA', youtubeStart: 20, youtubeEnd: 30, hint: '스페인의 정열적인 발 구르기 춤', answers: ['플라멩코', 'flamenco'], difficulty: 1 },
{ id: 'dn003', category: '춤의 종류', youtubeId: '9cNQFB0TDfY', youtubeStart: 0, youtubeEnd: 10, hint: '발끝으로 서서 추는 고전 춤', answers: ['발레', 'ballet'], difficulty: 1 },
{ id: 'dn004', category: '춤의 종류', youtubeId: 'dYHpIgj4SoM', youtubeStart: 30, youtubeEnd: 40, hint: '빠른 비트에 몸을 튕기는 거리 춤', answers: ['브레이크댄스', '비보이', 'breakdance'], difficulty: 1 },
{ id: 'dn005', category: '춤의 종류', youtubeId: 'zZQh4IL7unM', youtubeStart: 20, youtubeEnd: 30, hint: '쿠바에서 온 경쾌한 커플댄스', answers: ['살사', 'salsa'], difficulty: 1 },
{ id: 'dn006', category: '춤의 종류', youtubeId: 'Ava45CrcDPQ', youtubeStart: 10, youtubeEnd: 20, hint: '하와이 전통 손동작 춤', answers: ['훌라', 'hula', '훌라춤'], difficulty: 1 },
{ id: 'dn007', category: '춤의 종류', youtubeId: 'zy79KKpQ988', youtubeStart: 60, youtubeEnd: 70, hint: '아일랜드 전통 발 구르기 춤', answers: ['아이리시댄스', '리버댄스', 'irish dance'], difficulty: 2 },
{ id: 'dn008', category: '춤의 종류', youtubeId: 'mnbSrnGmErs', youtubeStart: 20, youtubeEnd: 30, hint: '탭 소리를 내며 추는 미국 춤', answers: ['탭댄스', 'tap dance'], difficulty: 1 },
{ id: 'dn009', category: '춤의 종류', youtubeId: 'He4qVF-AZxQ', youtubeStart: 20, youtubeEnd: 30, hint: '브라질 카니발의 화려한 춤', answers: ['삼바', 'samba'], difficulty: 1 },
{ id: 'dn010', category: '춤의 종류', youtubeId: 'cjaxe2m6n28', youtubeStart: 30, youtubeEnd: 40, hint: '빙판 위에서 추는 춤', answers: ['아이스댄싱', '피겨스케이팅', 'ice dancing'], difficulty: 1 },
{ id: 'dn011', category: '춤의 종류', youtubeId: 'uuF0OosXR78', youtubeStart: 15, youtubeEnd: 25, hint: '긴 치마를 돌리며 추는 한국 전통 춤', answers: ['부채춤', '한국무용', '전통무용'], difficulty: 2 },
{ id: 'dn012', category: '춤의 종류', youtubeId: '3X7x4Ye-tqo', youtubeStart: 30, youtubeEnd: 40, hint: '인도의 화려한 손동작 전통춤', answers: ['볼리우드댄스', '인도춤', 'bharatanatyam'], difficulty: 2 },
{ id: 'dn013', category: '춤의 종류', youtubeId: 's_sToZjPyHY', youtubeStart: 15, youtubeEnd: 25, hint: '엉덩이를 흔드는 중동 전통춤', answers: ['벨리댄스', 'belly dance'], difficulty: 1 },
{ id: 'dn014', category: '춤의 종류', youtubeId: 'kcFqCe6BSt4', youtubeStart: 30, youtubeEnd: 40, hint: '줄을 넘으며 추는 에너지 넘치는 춤', answers: ['점프스타일', '점핑댄스', 'jumpstyle'], difficulty: 3 },
{ id: 'dn015', category: '춤의 종류', youtubeId: 'hxzLIQMok78', youtubeStart: 20, youtubeEnd: 30, hint: '로봇처럼 움직이는 팝핀 춤', answers: ['팝핀', '로봇댄스', 'popping'], difficulty: 2 },
];

module.exports = { RAW_QUIZ_DATA };
